### PR TITLE
Update Robo and add composer.lock

### PR DESCRIPTION
**Pull request by danepowell**
Backport of #3384

### CODE REVIEW

**Comment by danepowell** [comment]
@alexxed I merged your PR to update Robo in 10.x, but for some reason when we try to update Robo in 9.2.x it fails tests. This is the main error I see: `Error: Class 'Symfony\Component\Config\Definition\Processor'`

Any ideas what's going on there?

If we can't get this updated in 9.2.x, we'll need to update the documentation to indicate that 9.2.x won't support Drush 9.6.

**Comment by alexxed** [comment]
I can't reproduce the error locally. I might be missing something compared to Travis.

Drush 9.6 was released 20 hours ago, this failing build was 15 hours ago and logs say it pulled Drush 9.6 (which does not depend directly on symfony/config anymore). So I suspect it's related to that, and not this PR.

If we use symfony/config in BLT we should require it as a direct dependency.

I restarted the build for the 10.0.x PR: https://travis-ci.org/acquia/blt/builds/498280959 ; if it fails then we have a confirmation that Drush 9.6 is causing this.

**Comment by alexxed** [comment]
Oh, can't run a build on a closed PR. Can you require symfony/config ^3.4 (this was what Drush 9.5 pulled) and see if the build passes?

**Comment by danepowell** [comment]
Adding a composer.lock file fixed this, as expected. I'm going to merge this as-is (without updating Drush) and then we'll start new PRs to update Drush, and I'll respond to your feedback there.

**Comment by alexxed** [comment]
This kind of confirms that drush 9.6 would break the tests as it did here as it doesn't pull symfony/config.

**Pull request merged**
