### PR TITLE
Run drush cr instead of using SQL query.

### LINKED ISSUE #3815: DT-729: TRUNCATE cache_entity caused subtle fatal MySQL error
**Describe the bug**
Recently, I am trying to upgrade BLT from 9.2.x to 10.x in our project.  When I run the new feature in the Travis-CI, the build failed subtly. So I have to debug each step to figure out what's going wrong. When I test `blt sync:db` on my local to sync DB from the Acquia test environment, I see error message `In SqlCommands.php line 199: Query failed.` After digging, it turns out `'sqlq "TRUNCATE cache_entity"'` in `blt sync:db` caused issue. 

In Acquia cloud, the cache bin defaults to `memcached` and there is not `cache_entity` table in our DB at all. So mysql get failed. Though, we see this issue in our current build, but we did not get fatal mysql error when we use `BLT 9.2.8` + `Drush 9.6.1`

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Config  on 'drush.aliases.remote' in the `blt/blt.yml` to the remote site hosted in the Acquia Cloud
2. Run `blt sync:db`
3. See error

**Expected behavior**
BLT should use drush cr to clear the cache instead of using raw SQL query.

**Detailed error output**

```
 [info] Executing: command -v mysql [0.31 sec, 10.44 MB]
 [info] sql:query: TRUNCATE cache_entity [0.32 sec, 11.05 MB]
 [info] Executing: mysql --defaults-file=/private/tmp/drush_WYUsVc --database=eaweb --host=mysql --port=3306 --silent -A < /private/tmp/drush_NoLBaR [0.32 sec, 11.05 MB]

In SqlCommands.php line 199:

  [Exception]
  Query failed.


Exception trace:
 () at /Users/ericchen/develop/code/eaweb2/vendor/drush/drush/src/Commands/sql/SqlCommands.php:199
 Drush\Commands\sql\SqlCommands->query() at n/a:n/a
 call_user_func_array() at /Users/ericchen/develop/code/eaweb2/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /Users/ericchen/develop/code/eaweb2/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /Users/ericchen/develop/code/eaweb2/vendor/consolidation/annotated-command/src/CommandProcessor.php:178
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /Users/ericchen/develop/code/eaweb2/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /Users/ericchen/develop/code/eaweb2/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/ericchen/develop/code/eaweb2/vendor/symfony/console/Application.php:987
 Symfony\Component\Console\Application->doRunCommand() at /Users/ericchen/develop/code/eaweb2/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /Users/ericchen/develop/code/eaweb2/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/ericchen/develop/code/eaweb2/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /Users/ericchen/develop/code/eaweb2/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /Users/ericchen/develop/code/eaweb2/vendor/drush/drush/drush.php:72
 require() at /Users/ericchen/develop/code/eaweb2/vendor/drush/drush/drush:4

sql:query [--result-file [RESULT-FILE]] [--file FILE] [--file-delete] [--extra EXTRA] [--db-prefix] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--database [DATABASE]] [--target [TARGET]] [--db-url DB-URL] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<query>]

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 02:09
```

**BLT doctor output**
+---------------------------+--------------------------------------------------------------+
| Property                  | Value                                                        |
+---------------------------+--------------------------------------------------------------+
| %paths.%root              | /Users/ericchen/develop/code/eaweb2/docroot                  |
| %paths.%site              | sites/default                                                |
| %paths.%modules           | sites/all/modules                                            |
| %paths.%themes            | sites/all/themes                                             |
| %paths.%config-sync       | ../config/default                                            |
| %paths.%config-dev        | ../config/dev                                                |
| %paths.%config-test       | ../config/test                                               |
| %paths.%config-mocha      | ../config/mocha                                              |
| %paths.%config-latte      | ../config/latte                                              |
| %paths.%config-prod       | ../config/prod                                               |
| %paths.%config-ra         | ../config/ra                                                 |
| %paths.%files             | sites/default/files                                          |
| %paths.%temp              | /tmp                                                         |
| %paths.%private           | /Users/ericchen/develop/code/eaweb2/files-private            |
| admin-theme               | seven                                                        |
| alias-searchpaths.0       | /Users/ericchen/develop/code/eaweb2/drush/sites              |
| blt-version               | 10.3.0                                                       |
| bootstrap                 | Successful                                                   |
| composer-version          | Composer version 1.8.6 2019-06-11 15:03:05                   |
| config-sync               | ../config/default                                            |
| db-driver                 | mysql                                                        |
| db-hostname               | mysql                                                        |
| db-name                   | eaweb                                                        |
| db-password               | root                                                         |
| db-port                   | 3306                                                         |
| db-status                 | Connected                                                    |
| db-username               | root                                                         |
| drupal-settings-file      | sites/default/settings.php                                   |
| drupal-version            | 8.6.17                                                       |
| drush-alias-files.0       | /Users/ericchen/develop/code/eaweb2/drush/sites/eadrupal.sit |
|                           | e.yml                                                        |
| drush-alias-files.1       | /Users/ericchen/develop/code/eaweb2/drush/sites/eaweb.site.y |
|                           | ml                                                           |
| drush-cache-directory     | /Users/ericchen/.drush/cache                                 |
| drush-conf.0              | /Users/ericchen/develop/code/eaweb2/vendor/drush/drush/drush |
|                           | .yml                                                         |
| drush-conf.1              | /Users/ericchen/develop/code/eaweb2/drush/drush.yml          |
| drush-conf.2              | /Users/ericchen/develop/code/eaweb2/docroot/sites/default/lo |
|                           | cal.drush.yml                                                |
| drush-script              | /Users/ericchen/develop/code/eaweb2/vendor/drush/drush/drush |
| drush-temp                | /tmp                                                         |
| drush-version             | 9.7.1                                                        |
| files                     | sites/default/files                                          |
| install-profile           | lightning_ea                                                 |
| modules                   | sites/all/modules                                            |
| php-bin                   | /usr/local/Cellar/php@7.2/7.2.17/bin/php                     |
| php-conf.0                | /usr/local/etc/php/7.2/php.ini                               |
| php-os                    | Darwin                                                       |
| private                   | /Users/ericchen/develop/code/eaweb2/files-private            |
| root                      | /Users/ericchen/develop/code/eaweb2/docroot                  |
| site                      | sites/default                                                |
| stacks.drupal-vm.inited   | false                                                        |
| stacks.dev-desktop.inited | false                                                        |
| temp                      | /tmp                                                         |
| theme                     | ea                                                           |
| themes                    | sites/all/themes                                             |
| uri                       | http://eaweb.localhost                                       |
+---------------------------+--------------------------------------------------------------+

**System information**
* Operating system type: macos
* Operating system version: 10.14.4
* BLT version: 10.3.0

**Additional context**

### PR DESCRIPTION
**Pull request by ericchenshine**
Fixes #3815
--------

Changes proposed
---------

- Use Drupal API to clear the cache instead of using raw SQL query.

### CODE REVIEW

**Comment by danepowell** [comment]
Thanks for the contribution. I actually don't see why we need to clear the cache here at all, we already do it a few lines above, plus Drush now clears the user entity cache during sql sanitization. Please review  https://github.com/acquia/blt/pull/3824 as an alternative fix.

**Comment by ericchenshine** [comment]
I think `drush.sanitize` could be disabled and we do disable it in our project. So we still need to clear the cache after DB sql or we have to rely on other tasks to clear cache first before run DB update and config import.

**Comment by danepowell** [comment]
Closing in favor of the fix I proposed above, rolled into #3824

**Comment by ericchenshine** [comment]
Sorry, totally forgot this thing. Yes this approach works perfectly 👍

**Pull request closed without merging**
