### PR TITLE
Fixes #4464 to increment Drush to version 11.x

### LINKED ISSUE #4464: Acquia BLT 13 will not allow projects to upgrade to Drush 11
**Background**
On January 11th, [Drush 11 was released](https://github.com/drush-ops/drush/releases/tag/11.0.0). With that release, support for Drush 10 was officially dropped.

Projects running the latest release of Acquia BLT are now forced to use an EOL version of Drush, as BLT mandates projects run Drush 10.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer require acquia/blt:^13.2.2 drush/drush:^11 -W`
2. See error `acquia/blt[13.2.2, ..., 13.x-dev] require drush/drush ^10.2.2 -> found drush/drush[10.2.2, ..., 10.x-dev] but it conflicts with your root composer.json require (^11)`

### PR DESCRIPTION
**Pull request by mikemadison13**
**Motivation**
Per #4464 Drush 10.x is now EOL (see https://github.com/drush-ops/drush/releases/tag/11.0.0) and we should be supporting 11.x.

**Proposed changes**
Increment:

- drush/drush to ^11
- remove argument that is passed into config import command per refactoring on Drush side, see https://github.com/drush-ops/drush/pull/4848/files and discussion in #4464

### CODE REVIEW

**Comment by smustgrave** [comment]
any timeframe on this PR? Would be greatly appreciated.

**Comment by richardbporter** [comment]
That definitely fixes the command error! I tried a few other commands as well. I don't know what the change means for backwards compatibility but maybe that doesn't matter since multiple config directories has been deprecated for a while.

**Comment by balsama** [comment]
> remove argument that is passed into config import command per refactoring on Drush side
Does this make BLT incompatible with Drush 10? I like the loose constraint, but if it's going to _fail_ with Drush 10 we should make 11 a requirement.

**Comment by balsama** [comment]
Noting that the failing job (INTEGRATED_TEST_ON_NEXT_MINOR_DEV, 7.4, FALSE) is expected since mysql56 module does not (yet) allow Drupal 9.4.

**Comment by balsama** [comment]
I'm actually not sure why Coveralls is reporting decreased coverage. I don't see how removing that argument method changes any code paths. Maybe fresh eyes tomorrow or someone who's more familiar with the way Coveralls tracks coverage will know.

**Comment by mikemadison13** [comment]
@balsama i noticed the coveralls change as well, and I have absolutely no clue why coverage would be dropping 3%, that seems super wonky based on the change(s) here.

**Comment by rahulgupta-acquia** [comment]
@mikemadison13 
 I created a PR with Improved Test Cases and Coverage Coverall (COVERAGE INCREASED (+0.9%) TO 42.636%) 
https://github.com/acquia/blt/pull/4470 

@balsama @shriacquia

**Comment by mikemadison13** [comment]
closing in favor of https://github.com/acquia/blt/pull/4470

**Pull request closed without merging**
