### PR TITLE
Adds a config value for deployment docroot.

### PR DESCRIPTION
**Pull request by b-sharpe**
Changes proposed
---------
Set the deploy docroot as config so it can be different than "docroot", this is helpful if your remote environment uses something other docroot such as pantheon which uses "web"

See #3740 for previous history

### CODE REVIEW

**Comment by danepowell** [comment]
Thanks for the contribution!

**Comment by danepowell** [comment]
Ugh... this has the unfortunate side effect of breaking deploys for anyone that sets a custom `deploy.dir` without also setting `deploy.docroot`. It appears that when you pass `deploy.dir` via the CLI, it's not incorporated into the value of `deploy.docroot` as we've defined it in config/build.yml. Robo has a few edge cases when it comes to recursion / order of operations with configuration, I guess this is one of them.

**Comment by danepowell** [comment]
I'm going to revert it in the 10.x branch for the above reason. 10.x should only have completely stable patch releases.

**Comment by b-sharpe** [comment]
@danepowell I'm not sure what to do here. The first PR ( #3740 ) was to keep things relative to repo root, in which case it was determined that it is usually defined to include repo root, but here you are saying that for deploy it would need to be relative or else it won't change when passed via CLI.

I'm happy to re-patch, but there needs to be a decision here. 

If we keep as above then someone passing to CLI `deploy.dir` also needs to pass `deploy.docroot` and it's just understood as with the repo root/docroot noted above. 

Otherwise, we need `deploy.docroot` to be relative, but then it functions different from the main one.

Let me know your thoughts here as we need this functionality to deploy to hosts not using `docroot`

**Pull request merged**
