### PR TITLE
BLT-000: drush8 compatibility issue with --config

### PR DESCRIPTION
**Pull request by alex-moreno**
Fixes sync:files broken for drush8.

Changes proposed:
- drush conf parameter should be --include-conf

### CODE REVIEW

**Comment by grasmash** [comment]
`Unknown option: --include-conf.`

**Comment by alex-moreno** [comment]
are you using drush9? That may be the issue !?

```$ drush --version
 Drush Version   :  8.1.15```

**Comment by alex-moreno** [comment]
actually: https://groups.drupal.org/drush/commands

but definitely -c breaks my blt sync:files

**Comment by grasmash** [comment]
No, the (failing) build is using 8.1.15: https://travis-ci.org/acquia/blt/builds/286519026#L700
https://travis-ci.org/acquia/blt/builds/286519026#L1565

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2121

**Pull request closed without merging**
