### PR TITLE
Fixing updates 9002000 message.

### PR DESCRIPTION
**Pull request by dpagini**
When update command runs and no factory hooks exist, this command errors.

This is against `9.2.x` - is that right? It's such a small error, but this gave me...

```sh
Notice: Undefined variable: messages in /var/www/project/vendor/acquia/blt/src/Update/Updates.php on line 625
```

### CODE REVIEW

**Comment by dpagini** [comment]
@mikemadison13 any thoughts on this guy?

**Comment by mikemadison13** [comment]
Let me have a look and see if I can reproduce the original issue!

**Comment by mikemadison13** [comment]
@dpagini any thoughts on how i can reproduce this more consistenly? i just nuked my factory-hooks directory and ran blt update...

```
blt update
Copying files from BLT's template into your project...
Merging BLT's blt.yml template with your project's blt/blt.yml...
Removing deprecated files and directories...
> blt:init:shell-alias
The BLT alias is already installed and up to date.
```

**Comment by mikemadison13** [comment]
Works fine @dpagini, nice simple fix.

**Pull request merged**
