### PR TITLE
Update ORCA to alpha18.

### PR DESCRIPTION
**Pull request by danepowell**
https://github.com/acquia/orca/releases/tag/v1.0.0-alpha17

This is awesome because we should get full deprecation testing now.

Blocked by:
- [x] #3627 to fix code style errors 
- [x] #3738 to fix deprecation tests
- [x] Figure out what to do about deprecated Behat context: https://github.com/jhedstrom/drupalextension/issues/537
- [x] https://github.com/acquia/orca/issues/27 to fix other deprecation tests
- [x] alpha17 release of ORCA to fix overzealous code style scanning (i.e. MD files)
- [x] Update coding-standards dependency version to match ORCA dependency in ~alpha17~ whatever version includes the library
- [x] Think about removing native PHPCS checks from BLT, since they would now duplicate ORCA.
- [x] Remove version constraint `mglaman/phpstan-drupal": "0.11.7"` introduced in #3739
- [x] Update to Symfony 4.x if we can to work around a deprecation scanning bug with ORCA

### CODE REVIEW

**Comment by danepowell** [comment]
This is either blocked by #3627, or we need to temporarily disable phpcs as referenced in the release notes

**Comment by danepowell** [comment]
We probably need to wait until after we update acquia/coding-standards to the latest version _and_ ORCA tags a new release that uses acquia/coding-standards.

**Comment by danepowell** [comment]
Alpha17 out now, should also fix phpstan neon issues: https://github.com/acquia/orca/releases/tag/v1.0.0-alpha17

**Comment by danepowell** [comment]
@TravisCarden do you have a timeline for releasing a new ORCA version that uses the shared Coding Standards library rather than ORCA's built-in standards? I think this will be necessary to get the static analysis tests passing here, since we developed to the shared standards rather than ORCA's (they are slightly different).

**Comment by TravisCarden** [comment]
@danepowell I'm working on a release as we speak. I'm hoping to get it out today. I'll let you know.

**Comment by TravisCarden** [comment]
All right, @danepowell. [v1.0.0-alpha18](https://github.com/acquia/orca/releases/tag/v1.0.0-alpha18), using our shared coding standards library, is out now!

**Comment by danepowell** [comment]
Just one final bug to squash before we can merge this.

@TravisCarden I think ORCA is erroneously throwing a deprecation error here: https://travis-ci.com/acquia/blt/jobs/214613419#L2026

Notice that BLT uses [symfony/config 3.4.29](https://github.com/acquia/blt/blob/10.x/composer.json#L43), and in that version the [function BLT is calling is _not_ deprecated](https://github.com/symfony/config/blob/29a33f66194fbe2ed4555981810f15fd8440e4a8/Definition/Builder/TreeBuilder.php#L42), so I don't think ORCA should be throwing this error.

**Comment by TravisCarden** [comment]
You're right, @danepowell: ORCA uses Symfony Config 4.3. I wonder if that constitutes a bug in phpstan. In any case, I'll see what I can do about it.

**Comment by danepowell** [comment]
I confirmed locally that if you use ORCA's phpstan binary, it causes this false positive. If you use BLT's phpstan binary, it works fine (even for the same version of phpstant).

I think what's happening here is that phpstan is autoloading from its own directory, which means that it autoloads the wrong version of symfony for deprecation testing. You can confirm this by unceremoniously killing ORCA's symfony config: `rm -rf vendor/symfony/config/`

After that tests will pass.

**Comment by TravisCarden** [comment]
@danepowell I've worked around the issue in https://github.com/acquia/orca/pull/33. I can't merge the change yet because it will cause my builds to fail until you unpin from `mglaman/phpstan-drupal:0.11.7` and cut a new release. So you can test this per usual:

```diff
diff --git a/.travis.yml b/.travis.yml
index ce2dc757..ba35f8ae 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -58,6 +58,7 @@ before_install:
   # Install ORCA.
   - git clone --branch ${ORCA_VERSION} --depth 1 https://github.com/acquia/orca.git ../orca
   - curl https://patch-diff.githubusercontent.com/raw/acquia/orca/pull/30.patch | git -C ../orca apply
+  - curl https://patch-diff.githubusercontent.com/raw/acquia/orca/pull/33.patch | git -C ../orca apply
   - ../orca/bin/travis/before_install.sh

 install:
```

My local testing indicates that you'll still have at least one problem to work out, but it works like before on the other packages I tested with, and I think based on that and the failure itself (see below) that the problem will have to be addressed in BLT. In other words, the ball is in your court. :)

```
$ orca phpstan --sut=acquia/blt
> '/Users/travis.carden/Projects/acquia/orca-build/vendor/bin/phpstan' 'analyse' '--configuration=/Users/travis.carden/Projects/acquia/orca/src/Task/DeprecatedCodeScanner/phpstan.neon' '--autoload-file=/Users/travis.carden/Projects/acquia/orca-build/docroot/autoload.php' '/Users/travis.carden/Projects/acquia/orca-build/vendor/acquia/blt'
  70/181 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  38%
Fatal error: During class fetch: Uncaught PHPStan\Broker\ClassAutoloadingException: Class Composer\Plugin\PluginInterface not found and could not be autoloaded. in /Users/travis.carden/Projects/acquia/orca-build/vendor/phpstan/phpstan/src/Broker/Broker.php:358
Stack trace:
#0 [internal function]: PHPStan\Broker\Broker->PHPStan\Broker\{closure}('Composer\\Plugin...')
#1 /Users/travis.carden/Projects/acquia/blt/src/Composer/Plugin.php(23): spl_autoload_call('Composer\\Plugin...')
#2 /Users/travis.carden/Projects/acquia/orca-build/vendor/composer/ClassLoader.php(444): include('/Users/travis.c...')
#3 /Users/travis.carden/Projects/acquia/orca-build/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/travis.c...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Acquia\\Blt\\Comp...')
#5 [internal function]: spl_autoload_call('Acquia\\Blt\\Comp...')
#6 /Users/travis.carden/Projects/acquia/orca-build/vendor/phpstan/phpstan/src/Broker/Broker.php(363): class_exists('Acquia\\Blt\\Comp...')
 in /Users/travis.carden/Projects/acquia/blt/src/Composer/Plugin.php on line 23
PHP Fatal error:  During class fetch: Uncaught PHPStan\Broker\ClassAutoloadingException: Class Composer\Plugin\PluginInterface not found and could not be autoloaded. in /Users/travis.carden/Projects/acquia/orca-build/vendor/phpstan/phpstan/src/Broker/Broker.php:358
Stack trace:
#0 [internal function]: PHPStan\Broker\Broker->PHPStan\Broker\{closure}('Composer\\Plugin...')
#1 /Users/travis.carden/Projects/acquia/blt/src/Composer/Plugin.php(23): spl_autoload_call('Composer\\Plugin...')
#2 /Users/travis.carden/Projects/acquia/orca-build/vendor/composer/ClassLoader.php(444): include('/Users/travis.c...')
#3 /Users/travis.carden/Projects/acquia/orca-build/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/travis.c...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Acquia\\Blt\\Comp...')
#5 [internal function]: spl_autoload_call('Acquia\\Blt\\Comp...')
#6 /Users/travis.carden/Projects/acquia/orca-build/vendor/phpstan/phpstan/src/Broker/Broker.php(363): class_exists('Acquia\\Blt\\Comp...')
 in /Users/travis.carden/Projects/acquia/blt/src/Composer/Plugin.php on line 23
```

**Comment by danepowell** [comment]
Upstream issue on the off-chance that there's some better way to work around this than to directly require `composer/composer` into the fixture: https://github.com/phpstan/phpstan/issues/2305

**Pull request merged**
