### PR TITLE
Fixes #3386 to add drupal check for deprecated module / theme code.

### PR DESCRIPTION
**Pull request by mikemadison13**
Fixes #3386 
--------

Changes proposed
---------
(What are you proposing we change? How does this impact end users? Are manual or automatic updates required?)

- adds the mglaman/drupal-check package to composer
- adds the `tests:deprecated:modules` command
- adds the `tests:deprecated:themes` command
- expands `blt validate` command to check modules and themes for deprecated code if `validate.deprecation` values are overridden in blt.yml. 

Steps to replicate the issue
----------
1. add validate.deprecation.modules and validate.deprecation.themes to blt.yml and set to try
2. run blt validate
3. confirm that drupal-check is running for both custom modules and themes.

Additional details
-----------
This is now possible thanks to work being performed in https://github.com/mglaman/drupal-check/issues/68

### CODE REVIEW

**Comment by mikemadison13** [comment]
Sample Output from the Govcon repository:

```
blt tests:deprecated:modules
Checking for Deprecated Code in docroot/modules/custom
[ExecStack] /Users/mike.madison/git/Drupal-GovCon-2017/vendor/bin/drupal-check -d /Users/mike.madison/git/Drupal-GovCon-2017/docroot/modules/custom
[ExecStack] Running /Users/mike.madison/git/Drupal-GovCon-2017/vendor/bin/drupal-check -d /Users/mike.madison/git/Drupal-GovCon-2017/docroot/modules/custom in /Users/mike.madison/git/Drupal-GovCon-2017
 12/12 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] No errors                                                                                                         
                                                                                                                        

[ExecStack] Done in 1.433s
macbookpro-mikemadison:Drupal-GovCon-2017 mike.madison$ blt tests:deprecated:themes
Checking for Deprecated Code in docroot/themes/custom
[ExecStack] /Users/mike.madison/git/Drupal-GovCon-2017/vendor/bin/drupal-check -d /Users/mike.madison/git/Drupal-GovCon-2017/docroot/themes/custom
[ExecStack] Running /Users/mike.madison/git/Drupal-GovCon-2017/vendor/bin/drupal-check -d /Users/mike.madison/git/Drupal-GovCon-2017/docroot/themes/custom in /Users/mike.madison/git/Drupal-GovCon-2017
 6/6 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ -------------------------------------------- 
  Line   twentyeighteen/twentyeighteen.theme         
 ------ -------------------------------------------- 
  92     Call to deprecated function format_date().  
 ------ -------------------------------------------- 

 ------ -------------------------------------------- 
  Line   twentynineteen/twentynineteen.theme         
 ------ -------------------------------------------- 
  92     Call to deprecated function format_date().  
 ------ -------------------------------------------- 

                                                                                                                        
 [ERROR] Found 2 errors                                                                                                 
                                                                                                                        

[ExecStack]  Exit code 1  Time 6.41s
[notice] Review Deprecation warnings and re-run.
[error]  Drupal Check in docroot/themes/custom failed. 
```

**Comment by danepowell** [comment]
@nateacquia are you okay with this as a new feature for BLT? I think it's worthwhile, but if we merge it we own it. The alternative would be to provide it as a plugin.

**Comment by mikemadison13** [comment]
in fairness, there isn't much to "own" (since we're literally just running the drupal-check command) but point taken :)

**Comment by mikemadison13** [comment]
we do need to decide if this is going in:
are projects
- opted in by default (meaning we set to true in config)
- opted out by default (meaning we set to false in config)

in either way it can be easily overridden. i'm leaning towards opted out by default (which is how this PR is structured).

**Pull request merged**
