### PR TITLE
8.9.x robo 1.2.x

### PR DESCRIPTION
**Pull request by timcosgrove**
Changes proposed:
- Update 8.9.x composer.json to use `"consolidation/robo": "~1.2.4"`, matching 9.x.

### CODE REVIEW

**Comment by mikemadison13** [comment]
restarting the build to see if that helps

**Comment by timcosgrove** [comment]
I doubt that my change caused that test failure, but I can run the tests locally to check that.

**Comment by mikemadison13** [comment]
trying to reproduce that error locally, let's see what i can find.

**Comment by mikemadison13** [comment]
this error would appear to be lightning related. bugging it over on D.O. see: https://www.drupal.org/project/lightning_core/issues/2976200

**Comment by mikemadison13** [comment]
closing in favor of https://github.com/acquia/blt/pull/2837 which addresses both this issue and the lightning_core issue. thank you @timcosgrove for the PR!

**Pull request closed without merging**
