### PR TITLE
#3148: Remove webflo/drupal-core-require-dev.

### PR DESCRIPTION
**Pull request by grasmash**
#3148

### CODE REVIEW

**Comment by danepowell** [comment]
We added webflo/drupal-core-require-dev to composer.required.json in 9.2.x so that folks could run things like core tests.

The dependencies for these tests are in core's require-dev. Ordinarily, if someone downloaded Drupal core directly and ran composer install on it, they'd get these dependencies automatically. But composer only pulls dev dependencies from the root composer.json, so users of BLT _don't_ get these dependencies unless BLT also includes them (via webflo/drupal-core-require-dev) in its own require-dev.

It seems like this PR will break people's ability to run core tests, among other things.

**Comment by mikemadison13** [comment]
@grasmash any thoughts on @danepowell's comments above?

**Comment by malcolmp** [comment]
Maybe move to composer.suggested.json? This dependency added some confusion to us when trying to update from core 8.6.2 to 8.6.3 because of it's dependency on "drupal/core": "8.6.2" without a version range constraint. This blocks a simple composer update drupal/core to get the latest core release. That's fine if you know that this requirement is there and you can update it as well, but otherwise may frustrate users.

**Comment by hugovk** [comment]
Please see https://github.com/acquia/blt/pull/3301 to update docs with the command to update Drupal core in BLT.

**Pull request closed without merging**
