### PR TITLE
Improve multisite generate command.

### PR DESCRIPTION
**Pull request by danepowell**
There were a few odd things happening with this command. Mainly, it wasn't setting the local db settings correctly. Also it was setting the remote drush alias as local. Defaults could be set better. Lots of code standards violations.

### CODE REVIEW

**Comment by danepowell** [comment]
See if we can fix generated local Drush aliases to include a `root`, pending discussion in #3204

**Comment by danepowell** [comment]
Bummer... this is now actually blocked by #3204. I think the problem is that we changed the default local alias from `self` to `@foo.local`, which wouldn't be a problem except that we're hitting the bug in #3204.

**Comment by greg-1-anderson** [comment]
Workaround: if you are expecting the cwd to be always at the project root, and your Drupal root is always at docroot, then you could set root to `${env.CWD}/docroot` for your local aliases. Didn't try it, but should work.

**Comment by danepowell** [comment]
Awesome thanks, I think it's actually `${env.cwd}` (lowercase) but that did the trick.

**Pull request merged**
