### PR TITLE
BLT-1852 assuming -y when prompting while executing something in blt

### LINKED ISSUE #1852: BLT Sync does not permit drush prompt
My system information:
* Operating system type: [osx]
* Operating system version: [10.12.5]
* BLT version: [8.9]

Output of `blt doctor`:
```
Drupal VM was detected. Running blt doctor inside of VM...
Executing command cd /var/www/secret_project/docroot/.. && /var/www/secret_project/docroot/../vendor/bin/drush cc drush && /var/www/secret_project/docroot/../vendor/bin/drush --include=/var/www/secret_project/docroot/../vendor/acquia/blt/drush blt-doctor -r /var/www/secret_project/docroot/../docroot inside of Drupal VM...
'drush' cache was cleared.                                             [success]
Changed current directory to /home/vagrant/.composer
+----------------------+--------------------------------------------------------------------------------+
| Property             | Value                                                                          |
+----------------------+--------------------------------------------------------------------------------+
| %paths               |                                                                                |
|  - %root             | /var/www/secret_project/docroot                                                         |
|  - %site             | sites/default                                                                  |
|  - %modules          | modules                                                                        |
|  - %themes           | themes                                                                         |
|  - %config-sync      | ../config/default                                                              |
|  - %files            | sites/default/files                                                            |
|  - %temp             | /tmp                                                                           |
| admin-theme          | seven                                                                          |
| blt-version          | 8.9.0                                                                          |
| bootstrap            | Successful                                                                     |
| config-sync          | ../config/default                                                              |
| db-driver            | mysql                                                                          |
| db-hostname          | localhost                                                                      |
| db-name              | drupal                                                                         |
| db-password          | drupal                                                                         |
| db-port              | 3306                                                                           |
| db-status            | Connected                                                                      |
| db-username          | drupal                                                                         |
| drupal-settings-file | sites/default/settings.php                                                     |
| drupal-version       | 8.3.5                                                                          |
| drush-alias-files    | /var/www/secret_project/docroot/../drush/site-aliases/aliases.drushrc.php               |
|                      | /var/www/secret_project/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
|                      | /var/www/secret_project/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
|                      | /var/www/secret_project/docroot/../drush/site-aliases/mtav2.aliases.drushrc.php         |
| drush-conf           | /var/www/secret_project/drush/drushrc.php                                               |
| drush-script         | /var/www/secret_project/vendor/drush/drush/drush.php                                    |
| drush-temp           | /tmp                                                                           |
| drush-version        | 8.1.12                                                                         |
| files                | sites/default/files                                                            |
| install-profile      | lightning                                                                      |
| local-drushrc        | /var/www/secret_project/docroot/sites/default/local.drushrc.php                         |
| local-settings       | /var/www/secret_project/docroot/sites/default/settings/local.settings.php               |
| modules              | modules                                                                        |
| php-bin              | /usr/bin/php                                                                   |
| php-conf             | /etc/php/5.6/cli/php.ini                                                       |
| php-os               | Linux                                                                          |
| root                 | /var/www/secret_project/docroot                                                         |
| site                 | sites/default                                                                  |
| temp                 | /tmp                                                                           |
| theme                | secret_project2                                                                         |
| themes               | themes                                                                         |
| uri                  | http://local.secret_project.com                                                         |
| user                 |                                                                                |
+----------------------+--------------------------------------------------------------------------------+
+---------------------------+----------------------------------------------------------------------------------+
| Check                     | Outcome                                                                          |
+---------------------------+----------------------------------------------------------------------------------+
| checkDocrootExists        | Found docroot.                                                                   |
| checkCoreExists           | Drupal core exists                                                               |
| checkSettingsFile         | BLT settings are included in settings file.                                      |
| checkLocalSettingsFile    | Found your local settings file.                                                  |
| checkLocalDrushFile       | Found your local drush settings file.                                            |
| checkUri                  | $options['uri'] is set.                                                          |
| checkUriResponse          | Received a response from site http://local.secret_project.com.                            |
| checkFileSystem:%files    | Public files directory is writable.                                              |
| checkFileSystem:%private  | Private files directory is not set.                                              |
| checkFileSystem:%temp     | Temporary files directory is writable.                                           |
| checkDbConnection         | Connected to database.                                                           |
| checkDrupalBootstrapped   | Bootstrapped Drupal via drush.                                                   |
| checkDrupalInstalled      | Drupal is installed.                                                             |
| checkCaching:page         | Drupal cache is disabled.                                                        |
| checkCaching:css          | CSS preprocessing is disabled.                                                   |
| checkCaching:js           | JS preprocessing is disabled.                                                    |
| checkCiConfig             | Git remotes are set in project.yml.                                              |
| checkComposer:require     | acquia/blt is in composer.json's require object.                                 |
| checkComposer:plugins     | hirak/prestissimo plugin for composer is installed.                              |
| checkBehat:exists         | Behat local settings file exists.                                                |
| checkBehat:root           | You have DrupalVM initialized, but drupal_root in tests/behat/local.yml does not |
|                           | reference the DrupalVM docroot.                                                  |
|                           |   Behat drupal_root is /Users/glen/sites/secret_project/docroot.                          |
|                           |   To resolve, run blt setup:behat.                                               |
| checkProjectYml:keys      | project.yml has no deprecated keys.                                              |
| checkAcsfConfig           | BLT settings are not included in your pre-settings-php include.                  |
|                           |   Add a require statement for "/../vendor/acquia/blt/settings/blt.settings.php"  |
|                           | to /var/www/secret_project/docroot/../factory-hooks/pre-settings-php/includes.php         |
| checkDrupalVm:alias       | drush.aliases.local exists your drush aliases file.                              |
| checkDrupalVm:remote-host | remote-host for @secret_project.local drush alias does not match vagrant_hostname for     |
|                           | DrupalVM.                                                                        |
|                           |   remote-host is set to  for @secret_project.local                                        |
|                           |   vagrant_hostname is set to local.secret_project.com for DrupalVM.                       |
|                           |    != local.secret_project.com                                                            |
| checkPhpDateTimezone      | PHP setting for date.timezone is correctly set                                   |
+---------------------------+----------------------------------------------------------------------------------+
```secret_project

When I run this command:
```
blt sync:refresh:all 
```

I get the following output:
```
> sync
> sync:db
> setup:settings
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/secret_project/vendor/bin/drush cache-clear drush --uri=default && /var/www/secret_project/vendor/bin/drush sql-drop --uri=default && /var/www/secret_project/vendor/bin/drush sql-sync @mtav2.test @secret_project.local --structure-tables-key=lightweight --create-db --sanitize --uri=default && /var/www/secret_project/vendor/bin/drush cache-clear drush --uri=default in /var/www/secret_project/docroot
'drush' cache was cleared.                                             [success]
Do you really want to drop all tables in the database drupal? (y/n): Cancelled.                                                              [cancel]
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 75  Time 4.249s
[error]   
[error]  Command `sync:db ` exited with code 75. 
[error]  Command `sync ` exited with code 1. 
```

And I expected this to happen:
I expected it to complete and end at a command prompt with a finished VM.

### PR DESCRIPTION
**Pull request by alex-moreno**
Fixes #1852 .

Changes proposed:
- assuming -y when prompting while executing something in blt

### CODE REVIEW

**Comment by grasmash** [comment]
I think that I'd prefer to fix the prompt rather than remove it.

**Comment by alex-moreno** [comment]
not sure this is the right approach though

**Comment by alex-moreno** [comment]
Agree @grasmash

**Comment by alex-moreno** [comment]
although I am having this issue not in Travis, but when doing blt sync to fetch remote changes to my local. I am having a look where I could fix this similarly

**Comment by alex-moreno** [comment]
similarly as in your PR: https://github.com/grasmash/bolt/commit/ec4779c44595f03707b3727ca12c761527027e72

**Comment by grasmash** [comment]
Are you using a non-bash shell? Can you try the command with `--interactive` ?

**Comment by alex-moreno** [comment]
blt sync --interactive ?

It returns

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--interactive" option does not exist.

I am using iTerm2 for Mac

**Comment by alex-moreno** [comment]
actually this is still broken, I can only execute the command when adding the

 ->assume(TRUE)

line

**Comment by grasmash** [comment]
@alex-moreno Did you test 8.x?

**Comment by grasmash** [comment]
Despite this approach being different than I would prefer, I'm going to merge it as a temporary fix. Too many people are encountering this issue and I would like to release a hot fix.

**Comment by alex-moreno** [comment]
yes, I tried downgrading blt and using the dev version too. Neither worked for me, but I couldn't make an intensive test

**Pull request merged**
