### PR TITLE
Disabling sql-sanitize for Drush 9.

### LINKED ISSUE #2078: SQL-Sanitize Removed from Drush 9
My system information:
* Operating system type: [replace]
* Operating system version: [replace]
* BLT version: 8.9.x-dev f1901309db4a999db0e7d54c6936452788ffa2dd

When I run this command:
```
blt sync
```

I get the following output:
```
 [error]  Unknown option: --sanitize.  See `drush help sql-sync` for available options. To suppress this error, add the option --strict=0. 
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 6.713s
[error]   
```

And I expected this to happen:

After digging into this, there is something odd going on with sql-sync in Drush 9. I have opened a bug in their issue queue to track this issue here: https://github.com/drush-ops/drush/issues/3013

### PR DESCRIPTION
**Pull request by grasmash**
Fixes #2078

### CODE REVIEW

**Comment by danepowell** [comment]
@grasmash it looks like the --no option in Drush 9 is broken, or at least poorly documented: https://github.com/drush-ops/drush/issues/3014

**Comment by grasmash** [comment]
Yeah but this was passing up until a couple of commits ago—we didn’t change any related code as far as I can tell. Are we pulling in a new version of drush?

**Comment by grasmash** [comment]
Looks like a new version came out yesterday. I’m willing to bet that our cache expired today and the new version is to blame.

**Comment by danepowell** [comment]
Yeah beta5 dropped yesterday, which removed the `--no` option: https://github.com/drush-ops/drush/releases/tag/9.0.0-beta5

**Comment by grasmash** [comment]
Where do you see that it removed the --no option?

**Comment by danepowell** [comment]
It was removed / refactored a couple times over the last month:
https://github.com/drush-ops/drush/commit/2b12e16daa9934c8f10a336d6f7293ca320e045d
https://github.com/drush-ops/drush/commit/e3064576e5072aa0b6a896958dbba44103b91c5b

**Pull request merged**
