### PR TITLE
Added frontend-web-test hook to BLT.

### PR DESCRIPTION
**Pull request by aweingarten**
Fixes https://github.com/acquia/blt/issues/1564

Changes proposed:
- Add a new frontend-web-test hook that fires inside the behat tests.
-

### CODE REVIEW

**Comment by grasmash** [comment]
Can you explain the need for this?

**Comment by aweingarten** [comment]
Need an ability to run front-end tests with a web-server, and installed drupal site present.   Doing this here seemed to be the safest way to accomplish this goal. 

Any other approach would likely result in a second duplicate robo target which could needlessly increase the build times.

**Comment by grasmash** [comment]
Why can't we just use frontend-test for this?

**Comment by aweingarten** [comment]
Nope because the webserver doesn't exist during frontend-test.  

We could totally have the front-end test recreate all the stuff that is done in the behat target but that seems redundant.

**Comment by grasmash** [comment]
Hm, it still doesn't make sense to me that we'd create a new target for this. Rather, it seems like we need to execute tests in a different order. E.g.,

```
blt run-server
blt tests:all
blt kill-server
```

We'd basically remove the server start/kill logic from the tests command and require that these be run manually.

**Comment by grasmash** [comment]
Closing in favor if #1615

**Pull request closed without merging**
