### PR TITLE
Revert "Revert "[10.0.x] Drupal testing enhancements." (#3348)"

### LINKED ISSUE #3346: New PHPUnit features make BLT internal tests unstable.
@greylabel We're getting frequent failures after merging https://github.com/acquia/blt/pull/3249. 

There are two issues I see:

* The log output has become too long to to view in browser. We need to make it less verbose. 
* Test builds fail with `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` This may be an issue with the new tests failing to kill background processes, or simply taking too long.

This is a beta blocker. We'll need to either resolve it quickly or else revert and refactor.

### PR DESCRIPTION
**Pull request by greylabel**
Fixes #3346
--------

Changes proposed: See #1787

### CODE REVIEW

**Comment by dpagini** [comment]
Could I ask is there anything outstanding on this work?

**Comment by danepowell** [comment]
This looks good to me, @greylabel anything you feel still needs to be done here? The "WIP" title just makes me nervous... :smile:

**Comment by greylabel** [comment]
I _think_ this should be fine to merge with one caveat. 

In #3346 @grasmash noted two issues that needed to be fixed.

> The log output has become too long to to view in browser. We need to make it less verbose

I addressed this in this PR by adding a new pipeline just for ensuring that all Drupal test suites succeed with both test runners.

> Test builds fail with No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself. This may be an issue with the new tests failing to kill background processes, or simply taking too long.

This point has not been directly addressed -- and is why there is there is still a WIP label on this PR, which I will remove now -- and may or may not be an issues still. The problem is that all the differential Travis builds are coming back green as you can see in this thread, but when this PR was merged previously, Travis would time out when running the same tests on the integrated code. I didn't see any obvious reasons why (see links in #3346) and since I don't have admin access to this project, couldn't really meaningfully debug in Travis. I could try to recreate the time out in a fork, but did have not have bandwidth to do so.

I would say we should merge this again and I can be available to help debug if we see the timeout issues return.

P.S. I have some future plans to extend and refactor this work, but getting this base piece in would be really helpful.

**Comment by dpagini** [comment]
To address the "output is too long" concern... is there just a _smaller_ test we could choose to run as part of the testing? That Quickedit one seemed to have like 90+ test entries in it.

**Comment by greylabel** [comment]
@dpagini Probably. I just picked a pretty random set of tests. Would be fine followup issue. Splitting all these tests into their own pipeline seems to address the original concern of Travis's out no longer being readable in the UI console.

**Comment by dpagini** [comment]
Yeah, seems fair... however, it probably slows tests down by creating 6 containers instead of 4 for every build now. Honestly, not my call, just thought I'd bring it up.

**Comment by danepowell** [comment]
It looks like it takes 5 minutes to spin up a new BLT project, and then 5 minutes to run the quickedit tests.

@greylabel if you can just find a smaller test suite I'll merge this.

I created https://github.com/acquia/blt/issues/3436 to follow up and reduce test length / verbosity, which we should do regardless of this PR.

**Comment by greylabel** [comment]
Sounds good. #3436 is a good call and there are certainly some improvement that can be made here.

**Comment by greylabel** [comment]
I simplified the tests overall and removed the Simpletest suite altogether from the tests as that will need to happen for Drupal 8.7 anyway.

**Comment by danepowell** [comment]
Thanks a lot for the contribution! Went ahead and merged, let's follow-up with new issues for any additional work.

**Comment by greylabel** [comment]
@danepowell Thanks for merging this. The last build this [PR](https://travis-ci.org/acquia/blt/builds/504868014) was green, but again there are timeouts for jobs when building the integrated [10.x](https://travis-ci.org/acquia/blt/builds/504915961) branch. Curious if you know any differences on how Travis runs for PRs vs branches that might cause this)?

See jobs https://travis-ci.org/acquia/blt/jobs/504868019 and https://travis-ci.org/acquia/blt/jobs/504915966 specifically.

**Comment by danepowell** [comment]
The only major difference I can think of is that PRs usually don't have access to encrypted environment variables.

At least now we can temporarily disable these tests without having to revert everything, which is what I've done for now. But we need to figure out what's going on. #3444

**Pull request merged**
