### PR TITLE
Add php5.6-yaml package

### PR DESCRIPTION
**Pull request by bobbygryzynger**
Changes proposed:
- Add php5.6-yaml package (which is now enabled on many Acquia environments) to Vagrant box.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Unfortunately, overriding `php_packages` in this way will blow out the rest of the list and cause many other necessary PHP packages to not be installed.

**Comment by grasmash** [comment]
@bobbygryzynger I'm reverting this PR.

**Comment by geerlingguy** [comment]
Note that Drupal VM's next release will include the `php[version]-yaml` package by default.

**Comment by bobbygryzynger** [comment]
Sounds good. Looking forward to the next release @geerlingguy.

**Comment by geerlingguy** [comment]
(I'm hoping to get time to tag/release today... else later this week).

**Pull request merged**
