### PR TITLE
Fixes #2129: PHPCS + New BLT behavior.

### LINKED ISSUE #2129: PHPCS + New BLT behavior
My system information:
* Operating system type: Mac
* Operating system version: 10.12.6
* BLT version: 8.9.8

Output of `blt doctor`:
```
+--------------------------+----------------------------------------------------------------------------------+
| Check                    | Outcome                                                                          |
+--------------------------+----------------------------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                                   |
| checkCoreExists          | Drupal core exists                                                               |
| checkSettingsFile        | BLT settings are included in settings file.                                      |
| checkLocalSettingsFile   | Found your local settings file.                                                  |
| checkLocalDrushFile      | Found your local drush settings file.                                            |
| checkUri                 | $options['uri'] is set.                                                          |
| checkUriResponse         | Received a response from site https://coresite.dd:8443.                          |
| checkHttps               | The SSL certificate for your local site appears to be invalid for                |
|                          | https://coresite.dd:8443.                                                        |
| checkFileSystem:%files   | Public files directory is writable.                                              |
| checkFileSystem:%private | Private files directory is writable.                                             |
| checkFileSystem:%temp    | Temporary files directory is writable.                                           |
| checkDbConnection        | Connected to database.                                                           |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                   |
| checkDrupalInstalled     | Drupal is installed.                                                             |
| checkCaching:page        | Drupal cache is disabled.                                                        |
| checkCaching:css         | CSS preprocessing is disabled.                                                   |
| checkCaching:js          | JS preprocessing is disabled.                                                    |
| checkCiConfig            | Git remotes are set in project.yml.                                              |
| checkComposer:require    | acquia/blt is in composer.json's require object.                                 |
| checkComposer:plugins    | hirak/prestissimo plugin for composer is not installed.                          |
|                          |   Run `composer global require hirak/prestissimo:^0.3` to install it.            |
|                          |   This will improve composer install/update performance by parallelizing the     |
|                          | download of dependency information.                                              |
| checkBehat:exists        | Behat local settings file exists.                                                |
| checkBehat:root          | You have DrupalVM initialized, but drupal_root in tests/behat/local.yml does not |
|                          | reference the DrupalVM docroot.                                                  |
|                          |   Behat drupal_root is /Users/bosborne/Projects/core-site/docroot.               |
|                          |   To resolve, run blt setup:behat.                                               |
| checkBehat:uri           | base_url in tests/behat/local.yml does not match the site URI.                   |
|                          |   Behat base_url is set to "http://coresite.dd:8083".                            |
|                          |   Drush site URI is set to https://coresite.dd:8443.                             |
| checkProjectYml:keys     | project.yml has no deprecated keys.                                              |
| checkDrupalVm            | Drupal VM is configured correctly.                                               |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                                   |
+--------------------------+----------------------------------------------------------------------------------+
```

I recently upgraded our project to BLT 8.9.x from a version on 8.8.x. I noticed that PHPCS is now scanning every one of my custom theme/module files in the precommit hook. I looked at the code and found this:

```
  /**
   * Validates staged files.
   *
   * @command git:pre-commit
   *
   * @param string $changed_files
   *   A list of staged files, separated by \n.
   *
   * @return int
   */
  public function preCommitHook($changed_files) {
    $this->invokeCommands([
      // Passing a file list to be PHPCS will cause all specified files to
      // be sniffed, regardless of the extensions or patterns defined in
      // phpcs.xml. So, we do not use validate:phpcs:files.
      'validate:phpcs' => [],
      'validate:twig:files' => ['file_list' => $changed_files],
      'validate:yaml:files' => ['file_list' => $changed_files],
    ]);

    $changed_files_list = explode("\n", $changed_files);
    if (in_array(['composer.json', 'composer.lock'], $changed_files_list)) {
      $this->invokeCommand('validate:composer', ['file_list' => $changed_files]);
    }

    $this->invokeHook('pre-commit');
    $this->say("<info>Your local code has passed git pre-commit validation.</info>");
  }
```

Previously BLT used to just pass the changed files. What changes prompted this, an upgrade of phpcs maybe? Basically I want to go back to the way it was before if possible.

What I've tried so far is to replace this command with my own and again start passing `$changed_files` to the `validate:phpcs:files` command, but that has the weird side effect of it scanning any file that is in the same directory as the changed files.

Anything I can pursue? Thank you!

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by dariusrestivan** [comment]
I understand it's been some disagreement around the new behaviour and the newer one works better, but can we make a workaround like an argument for phpcs to sniff only the locally modified files added for commit, like it used to be? Change the default behaviour but keep the older one for the people who still want it.

**Comment by bkosborne** [comment]
Is there anyway we can remove [this](https://github.com/grasmash/bolt/blob/6b59ad8fe87485d5b2d127bc01f6cdc32693a714/src/Robo/Commands/Validate/PhpcsCommand.php#L68) too?

Or maybe it was always like that? Scanning all the files in the directory of the changeset?

**Comment by grasmash** [comment]
@dariusrestivan 

> but can we make a workaround like an argument for phpcs to sniff only the locally modified files added for commit, like it use to?

That is exactly what this pull request is attempting to accomplish.

**Comment by grasmash** [comment]
@bkosborne Good catch. I'll have to test if removing that affects the behavior.

**Comment by cosmicdreams** [comment]
It's great that this was accomplished, but it would be awesome if this was backported to the 8.x series.  We haven't moved to 9.x yet and would like to re-enable phpcs so that it works as we previously expected.

**Pull request merged**
