### PR TITLE
Fixes the sanitize function to use the configured docroot.

### PR DESCRIPTION
**Pull request by b-sharpe**
Simply changes the sanitize function of deployment to use the configured docroot instead of being hard-coded.

### CODE REVIEW

**Comment by danepowell** [comment]
Why would you want to do this?

`docroot` is typically defined as `${repo.root}/docroot`: https://github.com/acquia/blt/blob/736e40ff107e69ed39a27d462578b1275fe338de/config/build.yml#L60

Wouldn't this change then cause deploy operations to happen in `${repo.root}/deploy/${repo.root}/docroot`, which is a nonsensical path?

**Comment by b-sharpe** [comment]
@danepowell Because docroot should be configurable. Just because Acquia uses it as it's default doesn't mean every host does. Pantheon for example uses "web" and some other hosts use "html"

Every other function seems to allow it to be configurable, but since santize does not and is part of the artifact:deploy script, it prevents deployment if not using docroot

**Comment by danepowell** [comment]
I see. That makes sense, but I think the implementation is going to need some work because as I mentioned above, `docroot` is typically defined to include the `repo.root`. You would need a separate configuration variable for just the docroot name.

**Comment by danepowell** [comment]
Closing due to failing tests and lack of response. If you'd like to respond to the feedback above and clean up the PR, feel free to reopen.

**Pull request closed without merging**
