### PR TITLE
Speed up composer operations.

### PR DESCRIPTION
**Pull request by grasmash**
Backport https://github.com/acquia/blt/pull/3287 to 9.2.x.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Odd, seems like the test fails are unrelated?

**Comment by grasmash** [comment]
Yeah, no idea why this is failing.

**Comment by mikemadison13** [comment]
re-running just to see if that helps

**Comment by lcatlett** [comment]
I proposed a fix in #3336 so can backport once that is reviewed and merged

**Pull request merged**
