### PR TITLE
[console] Update Drupal Console to 1.0 ver.

### PR DESCRIPTION
**Pull request by jmolivas**
Update to latest supported Drupal Console version.

### CODE REVIEW

**Comment by grasmash** [comment]
Please update the lock file as well.

**Comment by jmolivas** [comment]
@grasmash thanks, yes I needed and updated DrupalConsole https://github.com/hechoendrupal/DrupalConsole/blob/master/composer.json#L39 to be able to update the composer.lock file.

Tagging a new DC release, re-run `composer require drupal/console` and then I will update the PR.

**Comment by jmolivas** [comment]
@grasmash I am getting this error when executing `composer require drupal/console:~1.0`
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/console ~1.0 is satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by grasmash** [comment]
I think you'll need to add:

```
"minimum-stability": "beta"
```

**Comment by grasmash** [comment]
Failure is unrelated. Merging.

**Pull request merged**
