### PR TITLE
Implements #1345 by making delay configurable.

### LINKED ISSUE #1345: Make Selenium and PhantomJS startup delay configurable.
When running Behat tests there is a significant delay (10-15 seconds) while BLT waits for the Selenium or PhantomJS servers to become available. It would be nice if this was configurable for  impatient folks like myself.

### PR DESCRIPTION
**Pull request by swichers**
Fixes #1345  .

Changes proposed:
- Adds configurable delay instead of a static one.

### CODE REVIEW

**Comment by grasmash** [comment]
The tests commands are being moved to https://github.com/acquia/blt/blob/8.x/src/Robo/Commands/Tests/BehatCommand.php. The tests.xml file will be removed before the next release. Could you please submit a PR with a modification to the Robo file?

**Comment by swichers** [comment]
Correct me if I am wrong, but the new implementation doesn't have a static delay. Instead it waits for a URL, no?

```
  $this->getContainer()->get('executor')->waitForUrlAvailable($this->seleniumUrl);
```

If so then that renders this change unnecessary.

**Comment by grasmash** [comment]
Well it does max out at 15 seconds: https://github.com/acquia/blt/blob/5dda56486b8b50a5750876d43d273b02c25b6976/src/Robo/Common/Executor.php#L124

**Comment by swichers** [comment]
Functionally before you had to wait 15 seconds no matter what, with this it has the chance to return much sooner with a cap of 15. That sounds good to me. I don't think this change adds much to the new code, but I can update if you want. Should I continue?

**Comment by grasmash** [comment]
Nah, I'm fine leaving it how it is.

**Pull request closed without merging**
