### PR TITLE
#249: Adding yaml parser to git-commit hook

### PR DESCRIPTION
**Pull request by msherron**

### CODE REVIEW

**Comment by grasmash** [comment]
Looks like the contents of parse-yaml.sh might be wrong?

**Comment by msherron** [comment]
woops, updated :)

**Comment by grasmash** [comment]
This seems like a great idea, but I'm hesitant to use bash string parsing to find this value. Adding a yaml:get command to drupal/console that leverages Symfony's yaml parser seems like a more reliable path forward.

See https://github.com/hechoendrupal/DrupalConsole/tree/master/src/Command/Yaml

**Comment by grasmash** [comment]
Pinging @jmolivas in case he has an opinion on adding something like `yaml:get:value [key] [filename]` to Drupal Console.

**Comment by grasmash** [comment]
See https://github.com/hechoendrupal/DrupalConsole/pull/2553

**Comment by grasmash** [comment]
`yaml:get:value [filename] [key]` has been added to drupal console and released in beta5.

**Comment by grasmash** [comment]
Closing in favor of https://github.com/acquia/blt/pull/256

**Pull request closed without merging**
