### PR TITLE
Updating composer to use d.o packagist.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
Seems like this doesn't download lightning.

**Comment by geerlingguy** [comment]
@grasmash - I know there is an issue with distributions and composer on Drupal.org: [Give installation profiles/distributions GPLv3+ license as option for packaged downloads](https://www.drupal.org/node/1449452).

**Comment by grasmash** [comment]
Lightning is being downloaded, but it does not include the drupal.org make file.

**Comment by grasmash** [comment]
This is failing because distros are not yet supported by d.o packagist: https://www.drupal.org/node/2718229

downloading drupal/lighting actually downloads a full D8 docroot to docroot/profiles/contrib/lightning.

**Pull request closed without merging**
