### PR TITLE
Make phpcs test first test

### PR DESCRIPTION
**Pull request by CashWilliams**
Moves phpcs to the first test that is run. If phpcs does not pass, there is no sense in doing a full install.

### CODE REVIEW

**Comment by CashWilliams** [comment]
This also changes where the coder standard lives, from the target to blt itself.

**Comment by CashWilliams** [comment]
no travis test? 😢

**Comment by grasmash** [comment]
Yeah that's weird. May need to amend and re-push.

**Comment by grasmash** [comment]
Closed in favor of rebase #127

**Pull request closed without merging**
