### PR TITLE
Fixes #3998: Support PHP 7.4

### LINKED ISSUE #3998: DT-1165: PHP 7.4 incompatibility
Running any BLT commands under PHP 7.4 will result in an error. This is due to an upstream incompatibility: https://github.com/consolidation/Robo/issues/922

### PR DESCRIPTION
**Pull request by danepowell**
Fixes #3998 

Commands fail on PHP 7.4, so let's test that.

Also bump Drupal head.

### CODE REVIEW

**Comment by danepowell** [comment]
Tests fail as expected, waiting for upstream fix...

**Comment by danepowell** [comment]
Blocked on a new release of Robo, which likely won't come until after https://github.com/consolidation/Robo/pull/924 is resolved.

**Comment by greg-1-anderson** [comment]
#924 has now been merged to master; the backport to the 1.x branch is https://github.com/consolidation/Robo/pull/925.

**Comment by greg-1-anderson** [comment]
Please try with HEAD of the 1.x branch, and, if possible, HEAD of master.

**Comment by danepowell** [comment]
@greg-1-anderson thanks for the quick response. Head of 1.x is still failing, which makes sense as this commit hasn't been backported: https://github.com/consolidation/Robo/commit/2d2a4f6ad4019e612aab57a49f23956917c5cc5c

I'm not able to test the master branch with BLT because it conflicts will all versions of Drupal due to its Symfony dependencies. Drupal 8 uses Symfony 3 and Drupal 9 uses 4.4.3.

**Comment by greg-1-anderson** [comment]
Whoops, I thought I already had #922 backported to the 1.x branch, but I forgot. That's coming right up.

I'll try to loosen up some of the master branch requirements at a future date.

**Comment by greg-1-anderson** [comment]
OK, the 1.x branch now has https://github.com/consolidation/Robo/pull/922 on it.

**Comment by danepowell** [comment]
Yay, I can confirm that Robo 1.x-dev fixes it!

**Comment by greg-1-anderson** [comment]
Cool I will make a release pretty soon.

**Comment by greg-1-anderson** [comment]
Tagged 1.4.12.

**Comment by danepowell** [comment]
Woot, thanks! I'll bump our dependency on Robo to 1.4.12.

FYI, we'll try to switch to Robo 2 after updating our dependencies to support Drupal 9, and sorting out the conflict with Robo's Symfony versions.

**Comment by greg-1-anderson** [comment]
Tagged Robo 2.0.3 with slightly relaxed dependency constraints. Can be required in a project that uses the Drupal 9.0.0-alpha1 lock file.

**Comment by danepowell** [comment]
This is now blocked on a new release of Drush 10, which also has a PHP 7.4 incompatibility that was recently fixed in dev: https://github.com/drush-ops/drush/issues/4319

**Pull request merged**
