### PR TITLE
Fixes #3086: Install sites from existing config.

### LINKED ISSUE #3086: Support the "install site from existing config" feature of 8.6
I don't see an issue for this but I could be missing it. There are a few other "install from existing config" issues but none of them are referring to the feature being built into 8.6 as far as I can tell.

See https://www.drupal.org/project/drupal/issues/1613424 and https://www.drupal.org/project/drupal/issues/2980670 - Drupal 8.6 now has built-in support for installing from configuration directly rather than doing what BLT is currently doing which is to install the site and then import from configuration directly afterwards. 

Does BLT have plans to support this? I'd love to be able to just run `blt setup` and have it just work, as opposed to splitting out the `drush site-install --existing-config` myself.

### PR DESCRIPTION
**Pull request by danepowell**
Fixes #3086
--------

Changes proposed:
---------
For sites that store their configuration in the `config/default` directory (the default BLT configuration and the vast vast majority of sites I suspect), tell Drush to install the site from existing configuration. This is significantly faster than installing the site and then having to synchronize configuration afterwards.

Steps to replicate the issue:
----------
1. Create a new BLT project from scratch, including a VM if that's your thing.
2. Run `blt setup`
3. Run `drush cex`
4. Run `blt setup` once more (imagine that you are running this in the cloud for instance)

Observe that setup takes quite a while, since BLT first installs the site and then imports configuration changes.

Note that these steps will install Lightning. If you are using some other profile that implements hook_install, this will fail.

Steps to verify the solution:
-----------
1. Apply this patch
2. Repeat all of the steps above.
3. Verify that the behavior is exactly the same (because you haven't opted in).
4. Edit blt.yml and set cm.core.install_from_config to true.
5. Run `blt setup` again.

Observe that setup is blazingly fast by comparison, because the site is installed directly from existing config, and when the subsequent config import takes place, no changes need to get imported.

More details
----
Drupal internally refers to `config/default` as the 'sync' directory, which is why we key off of that. I'm not sure if we should make this optional or not. I'm not sure why you _wouldn't_ want to install a site from existing config, but it's a pretty new feature (as of Drupal 8.6 and Drush 9.4) so it could still be buggy, and maybe people just don't like change :man_shrugging:

### CODE REVIEW

**Comment by danepowell** [comment]
Ah, thank you failing tests. Apparently we also need to check here if there's actually anything to import. And I suppose we should verify the cm strategy. Basically all of the same checks we'd have during the later config import.

**Comment by mikemadison13** [comment]
@danepowell SIGNIFICANT explosions for me in BLT 9.2.x when i tried to run this patch with an existing project:

```
Running /var/www/<project>/vendor/bin/drush @self site-install <project> install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --sites-subdir=default --site-name=<project> --site-mail=no-reply@acquia.com --account-name='F+T7MWskd5' --account-mail=no-reply@acquia.com --locale=en --existing-config -v --ansi in /var/www/<project>/docroot
 [info] Executing: mysql --defaults-file=/tmp/drush_KgXyFV --database=drupal --host=localhost --port=3306 --silent -A < /tmp/drush_0gqv35 > /dev/null

 You are about to DROP all tables in your 'drupal' database. Do you want to continue? (yes/no) [yes]:
 > yes

 [info] Sites directory sites/default already exists - proceeding.
 [info] Executing: mysql --defaults-file=/tmp/drush_jJVxdh --database=drupal --host=localhost --port=3306 --silent -A < /tmp/drush_ojqvrB > /dev/null
 [info] Executing: mysql --defaults-file=/tmp/drush_AtUoQC --database=drupal --host=localhost --port=3306 --silent -A < /tmp/drush_z97V1W
 [info] Executing: mysql --defaults-file=/tmp/drush_iS79xY --database=drupal --host=localhost --port=3306 --silent -A < /tmp/drush_XltfHi
 [info] Installing from existing config at /var/www/<project>/config/default
 [notice] Starting Drupal installation. This takes a while.

In install.core.inc line 2297:
                                                                                                                   
  [Drupal\Core\Installer\Exception\InstallerException]                                                             
  Configuration install: <project>                                                                                    
                                                                                                                   
  The selected profile has a hook_install() implementation and therefore can not be installed from configuration.  
                                                                                                                   

Exception trace:
 install_display_requirements() at /var/www/<project>/docroot/core/includes/install.core.inc:1101
 install_verify_requirements() at /var/www/<project>/docroot/core/includes/install.core.inc:715
 install_run_task() at /var/www/<project>/docroot/core/includes/install.core.inc:590
 install_run_tasks() at /var/www/<project>/docroot/core/includes/install.core.inc:125
 install_drupal() at /var/www/<project>/vendor/drush/drush/includes/drush.inc:238
 drush_call_user_func_array() at /var/www/<project>/vendor/drush/drush/includes/drush.inc:223
 drush_op() at /var/www/<project>/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php:141
 Drush\Commands\core\SiteInstallCommands->install() at n/a:n/a
 call_user_func_array() at /var/www/<project>/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /var/www/<project>/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/<project>/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/<project>/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/<project>/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/<project>/vendor/symfony/console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /var/www/<project>/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/<project>/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/<project>/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /var/www/<project>/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /var/www/<project>/vendor/drush/drush/drush.php:66
 require() at /var/www/<project>/vendor/drush/drush/drush:4

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 13:50
[error]  Failed to install Drupal! 
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/<project>/vendor/bin/drush @self cset system.site page.front /node -y -v --ansi in /var/www/<project>/docroot
 [info] Executing: mysql --defaults-file=/tmp/drush_Sm20fs --database=drupal --host=localhost --port=3306 --silent -A < /tmp/drush_Q4wnwk > /dev/null
 [info] Executing: mysql --defaults-file=/tmp/drush_tRhQMH --database=drupal --host=localhost --port=3306 --silent -A < /tmp/drush_vVLm1z > /dev/null
 [notice] Missing database table: key_value

In Application.php line 238:
                                                                                                                                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]                                                                                                                  
  Command cset was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.  
                                                                                                                                                                                  

Exception trace:
 Drush\Application->bootstrapAndFind() at /var/www/<project>/vendor/drush/drush/src/Application.php:191
 Drush\Application->find() at /var/www/<project>/vendor/symfony/console/Application.php:229
 Symfony\Component\Console\Application->doRun() at /var/www/<project>/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/<project>/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /var/www/<project>/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /var/www/<project>/vendor/drush/drush/drush.php:66
 require() at /var/www/<project>/vendor/drush/drush/drush:4

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 0.552s
[error]  Failed to set the homepage 
```

**Comment by danepowell** [comment]
Ah, yeah... so that's a lot of errors, but it really just boils down to one simple problem, that your profile is using an install hook. You can't install profiles from existing config if they contain install hooks (since those hooks tend to tamper with config outside of the standard sync system).

Try testing again with Lightning or removing the install hooks and it should work fine.

I guess we need to make this feature optional and opt-in then.

**Comment by danepowell** [comment]
Latest commit makes this opt-in. I updated the testing steps accordingly. Should be ready to test again.

**Comment by danepowell** [comment]
@mikemadison13 that patch only removes hook_install from the subprofile _template_. So it will prevent a hook_install from being created in a new profile, but for your existing profile you'll need to manually remove that hook.

**Comment by mikemadison13** [comment]
@danepowell i think we can get this merged, it would be nice to add some basic docs to the config page.

**Comment by mikemadison13** [comment]
@danepowell i thought i was finally making progress, but alas...

getting a new error:

```
 [Drupal\Component\Plugin\Exception\PluginNotFoundException]  
  The "taxonomy_term" entity type does not exist. 
```

**Comment by brooke-heaton** [comment]
@danepowell is there any way this solution could be implemented in a BLT with multisite setup?

**Comment by brooke-heaton** [comment]
@danepowell Followed the steps. Received similar error as @mikemadison13 

```
In EntityTypeManager.php line 133:
                                                               
  [Drupal\Component\Plugin\Exception\PluginNotFoundException]  
  The "node" entity type does not exist.     
```

**Comment by brooke-heaton** [comment]
@mikemadison13 in my case, this may have been caused the the lack of a dependency on `drupal:node` in a custom module. Are you using any custom modules that should declare a dependency on `drupal:taxonomy` in the info file?

**Comment by brooke-heaton** [comment]
Unfortunately I think this solution may not working with non-lightning install profiles. I'm getting 

`Site UUID in source storage does not match the target storage.`

**Comment by danepowell** [comment]
I think that error indicates that your site is not actually importing from existing config, i.e. the conditionals in this PR are bailing so drush doesn't get the `--existing-config` argument. Which you should be able to verify by using the `-vvv` flag with your BLT commands.

**Comment by mikemadison13** [comment]
@brooke-heaton that is very possible. i'll have a look at that. thanks

**Comment by brooke-heaton** [comment]
@danepowell @mikemadison13 Good News! This patch is working perfectly fine on my multisite, including on a config directory that is not `config/default`. I think setting the `cm.path` and `cm.key` is sufficient for a multisite to install from config. I suspect, but am not certain, that any config import errors that point to a plugin are likely a problem with insufficient dependencies in custom modules. Adding those dependencies got me over the errors. There were other tweaks needed, but mostly just fixing the paths and adding the `install_from_config` after patching.

**Comment by brooke-heaton** [comment]
That said, I only gained ~1 minute on my build :/ But I'll take it.

**Comment by brooke-heaton** [comment]
Also, regarding this:
> Unfortunately I think this solution may not working with non-lightning install profiles. I'm getting
> 
> `Site UUID in source storage does not match the target storage.`

.... It was because some idiot, <--- this guy, copied the `cm.key` from the subsite to the default sites `blt.yml` so it was doing what it was supposed to. The uuid issues is a non issue.

**Pull request merged**
