### PR TITLE
Make vendor name configurable.

### PR DESCRIPTION
**Pull request by greylabel**

### CODE REVIEW

**Comment by greylabel** [comment]
@grasmash -- can you kick Travis to test this again?

**Comment by grasmash** [comment]
I'm tempted to just replace the "acquia" in the template/composer.json with "your-organization". It's the only place that the variable would be used, so should we really make it a variable?

**Comment by grasmash** [comment]
Test has been kicked off again.

**Comment by greylabel** [comment]
@grasmash I agree this is a pretty trivial change, on the surface. I think the crux of the issue is whether we leverage a single file to hold project-specific config (`project.yml`), or if we are ok with config/variables/etc being spread throughout the BLT code and potentially undocumented. Personally, I would favor a more robust `project.yml` rather than need to make project-specific changes throughout the codebase.

**Pull request merged**
