### PR TITLE
Fixes #3357: Don't use relative path for memcache PSR-4 path registration

### LINKED ISSUE #3357: Fatal error during cache rebuild due to registered MemcacheBackendFactory.php path
My system information:
* Operating system type: Drupal VM
* Operating system version: Debian 9
* BLT version: 9.2.3

When I run this command:
```
drush cr
```

I get the following output:
```
Failed to log error: Warning: stat(): stat failed for phar:///usr/local/bin/drush/bin/modules/contrib/memcache/src/MemcacheBackendFactory.php in TYPO3\PharStreamWrapper\PharStreamWrapper->invokeInternalStreamWrapper() (line 453 of /var/www/ghc09ev/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php).
```

The Drush launcher ist installed as PHAR inside the Drupal VM by default and since the upgrade to 8.6.6/8.6.7 it gives me this error when rebuilding caches via Drush.
Of course this is not a direct BLT bug, but it is caused by the way, BLT registers the memcache PSR4 class path in its `memcache.settings.php` file:

```php
$class_loader->addPsr4('Drupal\\memcache\\', 'modules/contrib/memcache/src');
```
I investigated this a little and found that the following would solve the issue:
```php
$class_loader->addPsr4('Drupal\\memcache\\', DRUPAL_ROOT . '/modules/contrib/memcache/src');
```
I'd appreciate to see this changed soon ;)

Thanx in advance!

### PR DESCRIPTION
**Pull request by hctom**
Fixes #3357 
--------

Changes proposed:
---------
(What are you proposing we change?)

- Use absolute path during memcache PSR-4 class path registration

Steps to replicate the issue:
----------
(If this PR is not fixing a defect/bug, you can remove this section.)

1. Use Drupal VM with Drush Lanucher installed and Memcache set up for Drupal
2. Run `drush cr` and see the PHP fatal error message described in #3357

Steps to verify the solution:
-----------
(How does someone verify that this does what you think does?)

1. Use Drupal VM with Drush Lanucher installed and Memcache set up for Drupal
2. Run `drush cr` and see if error mentioned in #3357 is still thrown

### CODE REVIEW

**Comment by marcelovani** [comment]
The solution works for me

**Comment by danepowell** [comment]
@hctom BLT takes its memcache configuration directly from the memcache module README: https://cgit.drupalcode.org/memcache/tree/README.txt?h=8.x-2.x#n146

If this is a problem, it seems like it needs to be fixed upstream first.

Additionally, BLT does not currently support or recommend running memcache in a local development environment, and I cannot replicate this error in a Cloud environment.

If you can get this changed upstream, or reproduce it in a Cloud environment, then I would definitely reconsider this PR. Thanks!

**Comment by danepowell** [comment]
I filed an upstream issue and would like to wait and see if there's any traction before merging this: https://www.drupal.org/project/memcache/issues/3038440

**Comment by danepowell** [comment]
@lcatlett what prompted you to add the blocked label to this? Is there anything we should be aware of before merging?

**Comment by danepowell** [comment]
Sounds like we should use `$app_root` to be in line with upstream issue and core standards.

**Comment by lcatlett** [comment]
@danepowell I marked this and all the other memcache related issues as blocked because memcache 2.0 is still not supported or recommended by Acquia (see https://github.com/acquia/blt/issues/3220#issuecomment-437619164 and the internal PF tickets on this). When BLT made changes to these settings previously without coordinating with docs and engineering, it was a nightmare for both BLT and support.

**Comment by hctom** [comment]
I also thought about that, but `DRUPAL_ROOT` is used on many places in the BLT settings files - so I think this should be changed all at once in another ticket/PR

**Comment by hctom** [comment]
@lcatlett this issue occures when using memcache 2.0.0-alpha7, so I guess this doesn't have to be blocked by the stable release upgrade stuff.

**Pull request merged**
