### PR TITLE
Change suggested packages to suggest from require.

### LINKED ISSUE #1325: "vendor/acquia/blt/composer.suggested.json" causing issues with composer
My system information:
* Operating system type: OSX
* Operating system version: Sierra
* BLT version: 8.7.1

When I am updating lightning like this:
```
composer require acquia/lightning:^2.1.0
rm -rf vendor && composer install
```
I got all the correct updated dependencies.
Then I ran:
```
composer update
```
and it downgraded me to older versions. For instance:
```
Updating drupal/core (8.3.0 => 8.2.7) Loading from cache
```
Then I ran:
```
composer update
```
again. And nothing was updated.
Then I removed from my composer.json:
```
"vendor/acquia/blt/composer.suggested.json"
```
And ran composer update and I got all the correct dependencies again.

Need to figure out why the suggested json is causing this problem.

### PR DESCRIPTION
**Pull request by arknoll**
Fixes #1325.

### CODE REVIEW

**Comment by arknoll** [comment]
I am assuming due to the naming convention of the file that these packages should really just be suggestions rather than require.

**Comment by arknoll** [comment]
Tested. this does fix the issue.

**Comment by grasmash** [comment]
This functionality changes the composer.suggested.json file. The intention is to provide defaults that can be easily removed. This change would no longer include the packages. It would simply output a message indicating that these are suggested. 

I guess the real problem is that this changes the UX such that, to get a fully functioning code base with all suggested packages, the user would now need to run many composer require commands to download the suggested packages after creating the blt-based project.

**Comment by grasmash** [comment]
I'm closing this in favor of the solution in #1325.

**Pull request closed without merging**
