### PR TITLE
Replaced tivie/php-os-detector with drupol/phposinfo.

### LINKED ISSUE #3750: Use drupol/phposinfo
It seems that tivie/php-os-detector is a dependency and it can produces false results, see the corresponding issue: https://github.com/tivie/php-os-detector/issues/3

Based on this, I've created my own package: [drupol/phposinfo](https://packagist.org/packages/drupol/phposinfo) that fixes the issue.

This issue is to propose the replacement of tivie/php-os-detector with drupol/phposinfo.

### PR DESCRIPTION
**Pull request by danepowell**
Fixes #3750 
--------

Changes proposed
---------
- Replace tivie/php-os-detector, which can fail in some environments, with drupol/phposinfo, which should be more reliable and can also be called statically.
- Move some of these related functions into the EnvironmentDetector where they belong.

Should have no functional change for end users.

### CODE REVIEW

**Comment by danepowell** [comment]
@drupol let me know if this looks good to you

**Comment by drupol** [comment]
@danepowell Seems to be fine actually :-) Let's wait for the tests results.

**Comment by drupol** [comment]
Looks like the failures are not related to this change.

**Comment by danepowell** [comment]
Yeah it's an upstream bug, should be resolved shortly. Thanks for the contribution!

https://github.com/acquia/orca/issues/37

**Comment by drupol** [comment]
You're welcome :)

**Comment by drupol** [comment]
This PR mixes stuff, maybe a rebase instead of a merge would have been a better choice ?

**Comment by danepowell** [comment]
Ugh... not sure how that happened. I'll fix it.

**Pull request merged**
