### PR TITLE
It looks like @executeInDrupalVm crept back in to the sync:db command…

### PR DESCRIPTION
**Pull request by gabe-connolly**
… in 8.9.9, pulling it back out to re-enable successful database syncing from remote sites.

### CODE REVIEW

**Comment by grasmash** [comment]
Duplicate of https://github.com/acquia/blt/pull/2153 ?

**Comment by gabe-connolly** [comment]
@grasmash , you are correct that this is very close to #2153 .  It looks like I pulled out one more instance of syncDbAll from @executeInDrupalVm which wasn't in #2153 , but otherwise they are on the same track.

**Comment by grasmash** [comment]
I have resolved the conflict in the pull request.

**Comment by gabe-connolly** [comment]
@grasmash thanks!

**Pull request merged**
