### PR TITLE
Adds Bitbucket pipeline support.

### PR DESCRIPTION
**Pull request by b-sharpe**
- Adds an initial example Bitbucket CI configuration file.
- Adds a Robo task that copies the template to the project root.
- Adds a settings includes and bitbucket ci detection.

### CODE REVIEW

**Comment by TravisCarden** [comment]
@ba66e77 / @danepowell : @b-sharpe's company has decided to adopt BLT internally, and they need this Bitbucket support to get off the ground. Can we rustle someone up to provide some support? Thanks! 😃

**Comment by aweingarten** [comment]
A word of caution here.  While pipelines _technically_ supports bitbucket, in practices there are some nasty landmines here.   When I last tried this about 10 months ago bitbucket's API had a major limitation.  It didn't allow anyone including pipelines to pull in the branch from a fork inside a PR. It's a major limitation of the permission model of bit bucket.  Another manifestation is that you can't see a peer's branches unless you directly add them as collaborators to your fork .  

To work around I think pipelines is taking the patch/diff from bitbucket and applying that to the upstream branch to get a workable reproduction of the fork.  This works fine 80% of the time.  However, if you do a large refactor and move thousands of files this approach will fail. Somewhere it should be documented that bit-bucket is not a first class citizen in this ecosystem.

**Comment by danepowell** [comment]
@aweingarten @TravisCarden @b-sharpe I think there might be some confusion here.

I think the purpose of this issue to support Bitbucket's product called Pipelines, _not_ to add Bitbucket integration to _Acquia's_ product called Pipelines. Furthermore, I think Adam's comment was in reference to Acquia Pipelines. Is that correct?

Assuming so, I'll forward that comment to the Acquia Pipelines team to follow up on.

**Comment by b-sharpe** [comment]
@aweingarten While I agree BB has some limitations, I don't think that should hold up allowing people to use it with BLT. 

Most using BB should already be aware of these limitations, but I could put a doc page explaining the available process due to the limitations if that helps move this along?

Here are currently the different ways to deal with the limitations:

1. Don't fork. Smaller teams this works fine, as PRs from within the same Repo run pipelines with zero issue. BB supports a wide array of branch permissions, so you can even just lock develop/master merging to the Team Lead depending on your git workflow

2. Git Hooks. If forking, we can implement a new pre-commit that forces the same as a PR would (i.e. run behat tests). Then the PR can either be merged with just a code review, or if even further precaution is needed, then merge to a feature branch before develop/master to be tested.

3. Individual pipelines. If forking, pipelines can still run on the fork's repo, in which case while the PR to the upstream cannot run a pipeline, it CAN however see if the source's pipeline has passed or failed. This requires the fork to have pipeline minutes.

4. Your example. We do not use (or advise using) this method due to the issues you mentioned

As @TravisCarden mentioned, We are trying to trying to get our teams on board with using BLT, but unfortunately switching from BB is not an option at this point (and I would assume for other companies as well), so I am willing to contribute to moving this forward in any way I can.

**Comment by danepowell** [comment]
This looks really useful for folks using Bitbucket Pipelines, and we appreciate the contribution. Unfortunately, the BLT maintainers don't have infrastructure in place to access Bitbucket Pipelines or maintain features related to it, so we can't support it. Individual users can still use this PR as a reference and implement it themselves.

**Comment by danepowell** [comment]
I also suggest following #1793 as a means to provide Bitbucket Pipelines integration as part of a distributable package / plugin.

**Pull request closed without merging**
