### PR TITLE
Cleaned up ACSF init script.

### PR DESCRIPTION
**Pull request by danepowell**
Various parts of this were just broken.

### CODE REVIEW

**Comment by grasmash** [comment]
It looks like this just enables the acsf module before executing the init script. Is that necessary?

**Comment by danepowell** [comment]
Yes, the ACSF module needs to be enabled and Drupal needs to be bootstrapped (hence the addition of the drush aliases) in order for acsf_init to run.

**Comment by danepowell** [comment]
Having said that, I don't understand why tests are failing because Drupal can't be bootstrapped... I would have expected tests to fail _before_ this change...

**Comment by lcatlett** [comment]
I dont think drupal needs to be boostrapped to run acsf-init which is why it uses the includes.

**Comment by danepowell** [comment]
When I run this:
`drush --include=docroot/modules/contrib/acsf/acsf_init acsf-init`

I get this:
`Command acsf-init needs a higher bootstrap level to run`

So it does seem like Drupal needs to be bootstrapped. That's why I added the alias.

Once I added the alias, I ran the command without the acsf module enabled, and got this:
`Command acsf-init needs the following extension(s) enabled to run: acsf_init`

That seems like pretty clear evidence that Drupal has to be bootstrap and the module needs to be enabled, hence these changes.

**Comment by danepowell** [comment]
This documentation should also be added to the mkdocs

**Comment by danepowell** [comment]
I think Travis fails because ACSF init now needs to happen after Drupal can be bootstrapped

**Comment by danepowell** [comment]
This is hopelessly out of date

**Pull request closed without merging**
