### PR TITLE
Fix and update readme/creating-new-project.md

### PR DESCRIPTION
**Pull request by TravisCarden**
`readme/creating-new-project.md` has a few issues:

1. ~~It's missing a `composer install`. Following the steps _exactly as written_ today will result in an error.~~
1. The list formatting is broken.
1. There's [a minor grammar nerd issue](https://www.grammarly.com/blog/know-your-latin-i-e-vs-e-g/). 😛

### CODE REVIEW

**Comment by grasmash** [comment]
`composer install` should not be necessary?

**Comment by grasmash** [comment]
`composer install` should not be necessary? I think you had to run it to workaround https://github.com/acquia/blt/issues/2378. The fix for that needs to be released.

**Comment by grasmash** [comment]
Fix released. `composer install` should not be necessary now.

**Comment by TravisCarden** [comment]
Thanks, @grasmash. I've removed that commit.

**Pull request merged**
