### PR TITLE
Fixes #1083: Include acquia_purge module by default.

### LINKED ISSUE #1083: Purge varnish cache on deployment
When deploying to Acquia environment(s) can BLT automatically purge the varnish cache so changes are reflected on the site to anonymous users?

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
@aweingarten How do you feel about adding this as a default package?

**Comment by aweingarten** [comment]
I think it's premature.  Right now it will not work unless the client is enrolled in the cache tag invalidation alpha/beta program.

**Comment by grasmash** [comment]
Ok, glad I asked! I'm going to mark this as blocked until you think it's ready.

**Comment by grasmash** [comment]
@aweingarten Just checking in... what's the status of cache invalidation program? I'm considering just merging this. Users don't necessarily _have_ to enable it.

**Comment by aweingarten** [comment]
So this is likely not going to be viable for another 30-60 days. I wouldn't merge it lest people think that they can use this.

**Comment by grasmash** [comment]
@aweingarten It's been 119 days, is this ready yet?

**Comment by aweingarten** [comment]
Nope still in a closed beta :(

**Comment by jasonlttl** [comment]
I was just about to add acquia_purge to our distro and remembered seeing something about it in blt. The module description now makes it look like it's open to all now.

https://www.drupal.org/project/acquia_purge

> The Drupal 8 version has had 17 weeks of thorough testing in a series of private alpha and beta releases. As of now, the module is still officially marked as beta but considered to be stable quality and **now open for everyone to test**.

**Pull request closed without merging**
