### PR TITLE
Re-enable Drupal tests

### PR DESCRIPTION
**Pull request by danepowell**
The tests provided by #3351 fail whenever we merge them, but oddly not during the initial pull request.

It fails with a Travis timeout (10 minutes) with no output received.

https://travis-ci.org/acquia/blt/jobs/504950804

### CODE REVIEW

**Comment by danepowell** [comment]
I opened #3446 to help test this and the pattern holds... whenever tests run on a code branch in the upstream repo, they fail. But whenever they run on a PR, they pass.

The only thing I can think of that's different between these environments is the presence of encrypted environment variables (SSH keys I think).

**Comment by greylabel** [comment]
Could be worth taking another look at the raw output of #3351 and the [PR build that was green](https://api.travis-ci.org/v3/job/504868019/log.txt) and the [build with timeouts](https://api.travis-ci.org/v3/job/504915966/log.txt). There are definitely some formatting differences that are masked by the Travis UI.

**Comment by danepowell** [comment]
Yeah Travis has an upstream issue that it strips colors (and possibly breaks other things? Who knows...) in builds that contain secrets: https://github.com/travis-ci/travis-ci/issues/7967

**Comment by danepowell** [comment]
Sure enough, I removed the encrypted variables and it seems like everything is working now. In the absence of any better explanation, I'm blaming it on https://github.com/travis-ci/travis-ci/issues/7967

**Comment by danepowell** [comment]
Merged in #3460

**Comment by dpagini** [comment]
Wow, kudos to you two for tracking this down. This was a nasty little guy...!

**Pull request closed without merging**
