### PR TITLE
[WIP] Fixes #2157: Adding aliases command.

### LINKED ISSUE #2157: Port club `aliases` command to BLT
Port [club aliases command](https://github.com/acquia/club/blob/master/src/Command/ACAliasesCommand.php) to BLT https://github.com/acquia/club.

ACSF alias generation should not be ported, as it is part of https://github.com/acquia/acsf-tools. 

@msherron perhaps acsf-tools could be updated to use Symfony commands?

### PR DESCRIPTION
**Pull request by grasmash**
Fixes #2157 

This is a completely untested work in progress, and has only been opened to serve as a starting point for others to complete the work.

### CODE REVIEW

**Comment by grasmash** [comment]
This is a completely untested work in progress, and has only been opened to serve as a starting point for others to complete the work.

**Comment by grasmash** [comment]
This should be modified in a few ways:

- Site factory aliases should not be generated
- Aliases should be in YAML format as per Drush 9 compatibility requirements, rather than using the current twig templates.
- We should probably replace the curl commands with a library like guzzle. See https://github.com/acquia/blt/blob/9.1.x/src/Robo/Commands/Tests/SecurityUpdatesCommand.php#L24.

**Comment by danepowell** [comment]
This produces quite a few warnings about the Acquia SDK's use of abandoned guzzle libraries when it's installed. I'm not sure we want to have that in BLT, it's going to create a negative perception and unnecessary support requests. Not to mention the possible stability / security implications of relying on libraries that old.

**Comment by danepowell** [comment]
I confirmed that the Acquia PHP SDK is officially abandoned (and not even really an Acquia tool). If we want to use it, we should take over ownership and upgrade it to use N3.

**Comment by typhonius** [comment]
I've created a new project that uses Cloud API v2 (N3) here: https://github.com/typhonius/acquia-php-sdk-v2. If it makes sense to use that (or extend it) for this PR instead then hopefully it'll iron out bugs and catch edge cases.

**Comment by danepowell** [comment]
Awesome thanks, I'll check it out

**Comment by danepowell** [comment]
I'm trying to get authentication to work. I also need to figure out why tests are pulling stale versions of Drupal.

**Pull request merged**
