### PR TITLE
Use optimized classloader to resolve notices

### LINKED ISSUE #3148: Resolve "Could not scan for classes inside" notices
This is a follow-up to #3120: in BLT 10.0.x. these notices are generated on composer installs. See that issue for more information.

You can see an example of these errors in our tests: https://travis-ci.org/acquia/blt/jobs/438701163#L1411

> source:build:composer
[Exec] Running export COMPOSER_EXIT_ON_PATCH_FAILURE=1; composer install --ansi --no-interaction in /tmp/blt-sandbox-instance
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
(etc)

### PR DESCRIPTION
**Pull request by lcatlett**
Fixes #3148 
--------

Changes proposed:
---------

- Using a PSR-0 class loader requires a file_exists() check on paths to make sure the class exists when it's to be loaded. This is inefficient and also can result in "Could not scan for classes inside" notices each time a class is missing when the autoloader is dumped. BLT should use Composer's optimized ClassLoader to resolve this 

Steps to replicate the issue:
----------
(If this PR is not fixing a defect/bug, you can remove this section.)

1. 
2. 

Steps to verify the solution:
-----------
(How does someone verify that this does what you think does?)

1.
2.

### CODE REVIEW

**Comment by mikemadison13** [comment]
This DID fix the problem for me briefly... but after running and re-running composer update a few times it came back.

note that initially i nuked vendor and docroot/core, and cleared composer cache to get it to work the "first time."

**Comment by mikemadison13** [comment]
@geerlingguy any thoughts on the above?

**Comment by danepowell** [comment]
I wasn't able to get this patch to work inside the VM even following Mike's tips. The only thing I did differently from Mike was to install Drupal core from outside the VM, since that hangs (presumably due to NFS latency) when I do it inside the VM. Maybe that's one of the root causes of all of this in the first place.

**Comment by lcatlett** [comment]
I havent finished debugging yet to validate, but while debugging some issues that have come up in recent support tickets, I came across https://github.com/symfony/symfony/issues/29877 which may be related to this error in BLT

**Comment by lcatlett** [comment]
Update - I think the proposed bugfix in #3336 might help here as well

**Pull request closed without merging**
