### PR TITLE
Don't force the config directory to be "vcs" during deploys

### LINKED ISSUE #1013: Make the cm.core.config-dir property configurable
Ok, so I thought I could deal with this, but every time I'm prompted for a config directory when I do a config import or export I die a little inside :)

Here's the main issue where I brought this up: https://github.com/acquia/blt/issues/678

Basically, Drupal wants there to be a config directory labeled 'sync' (it complains if it doesn't exist), but [BLT wants there to be one labeled 'vcs'](https://github.com/acquia/blt/blob/c6b27ddf0b16b49bbc1632a56fb7c11f946a8201/phing/tasks/deploy.xml#L224).

My site only uses one actual config directory. As a result I have this snippet at the very bottom of my site's settings.php file:

```
$config_dir = dirname(DRUPAL_ROOT) . "/config/$site_dir";
$config_directories['sync'] = $config_dir;
$config_directories['vcs'] = $config_dir;
```

That way they are both defined and BLT and Drupal are happy.

But because of that, whenever I do a config export or config import, I'm prompted to chose one of those, even though they are the same.

What I suggest doing here is changing [this line](https://github.com/acquia/blt/blob/c6b27ddf0b16b49bbc1632a56fb7c11f946a8201/phing/tasks/deploy.xml#L224) so that it accepts a parameter instead of hardcoding "vcs". Then I could configure it on my project.yml file.

### PR DESCRIPTION
**Pull request by bkosborne**
Fixes #1013

### CODE REVIEW

**Comment by danepowell** [comment]
I'm fine with making the config directory configurable here, but I don't think we can remove it because deployments to ACE will start failing. On ACE it does need to be `vcs`.

**Comment by bkosborne** [comment]
Hmm yeah I understand. Don't want an unexpected change to break deployments.

Note that I'm just removing the property _override_ here. The `cm.core.config-dir` property still exists and is used by the config import target. [It defaults to the 'sync' directory.](https://github.com/acquia/blt/blob/a1668961af1b10186ad31e943f28b5c1ca1da239/phing/build.yml#L39)

I wonder how people on ACE handle the annoyance of having two config directories defined. I don't think Acquia should have defined this 'vcs' directory in their config file to begin with.

**Comment by danepowell** [comment]
Apparently you're not the only one :)

https://github.com/acquia/blt/issues/678

**Comment by geerlingguy** [comment]
This can be closed now, in light of https://github.com/acquia/blt/pull/1080, correct @grasmash ?

**Comment by grasmash** [comment]
Yes!

**Pull request closed without merging**
