### PR TITLE
Issue #2093: Replace Drush assume with no-interaction.

### LINKED ISSUE #2093: Fix usage of drush assume (--yes / --no)
If my understanding is correct, there is no difference between `--yes` and `--no-interaction` in Drush 9. Both simply use whatever the "default response" is for any prompts. Source: https://github.com/drush-ops/drush/issues/3014#issuecomment-334316826

There's no way to force either yes or no.

So I think we should just remove the "assume" option completely, and pass `--no-interaction` for all commands. Unless you want to have interactive commands as an option.

### PR DESCRIPTION
**Pull request by danepowell**
Fixes #2093

### CODE REVIEW

**Comment by danepowell** [comment]
Hmm. Apparently the default non-interactive response for `drush si` is `no`, which is problematic. We need a way to force site install non-interactively.

This is also confusing because I thought `--yes` and `--no-interaction` were equivalent in Drush 9. So I'm not sure why this PR would break tests. Seems like an undocumented "feature".

**Comment by grasmash** [comment]
Yeah I noticed some quirks when I was working on this issue, they don't appear to be equivalent.

**Comment by danepowell** [comment]
This is blocked on https://github.com/drush-ops/drush/issues/3082

**Comment by danepowell** [comment]
New upstream issue: https://github.com/drush-ops/drush/pull/3084

It sounds like Drush is actually going to preserve `--yes` and `--no`, along with `--no-interaction`, I'm just trying to confirm. So we'll have to think more carefully about which of the three options to use.

**Comment by danepowell** [comment]
We should be able to use --no-interaction for site installs in Drush 9 beta8

**Pull request merged**
