### PR TITLE
10.0.x: Upgrade to Drupal 8.6.1

### PR DESCRIPTION
**Pull request by hugovk**
Changes proposed:
---------
(What are you proposing we change?)

- Upgrade to Drupal 8.6.1
- Was released on 2018-09-10
- https://www.drupal.org/project/drupal/releases/8.6.1

### CODE REVIEW

**Comment by danepowell** [comment]
@hugovk is there some reason that this upgrade is required for BLT users?

Note that the way we have defined the Composer dependency, anyone can easily upgrade to 8.6.1 without this change. The only effect of this PR will be to _mandate_ people use 8.6.1, which I don't think we should do unless there's a compelling reason.

**Comment by hugovk** [comment]
Oops, I misinterpreted the `^` operator, and `^8.6.0` will indeed allow upgrade to 8.6.1 as well. I'll close this, sorry for the noise!

By the way, is there a schedule for the release of 9.2.0 from alpha? We're looking forward to upgrading from 8.5 to 8.6. Thanks!

**Comment by danepowell** [comment]
No worries, thanks for trying to contribute.

I'm not aware of anything blocking a new 9.2 release, let me take a look at that today and see what makes sense.

**Comment by danepowell** [comment]
Good news, 9.2.0 is out now!

**Comment by hugovk** [comment]
Brilliant, thank you!

**Pull request closed without merging**
