### PR TITLE
Fixes #898: Upgrade to Drupal VM 4.1.0.

### LINKED ISSUE #898: Upgrade to Drupal VM 4.1.0
It has been released, and is better for projects that use styleguides, since `index.html` paths will work correctly (in the past, Apache would try loading `index.php` but not `index.html` when visiting paths like `example.com/theme/styleguide/`).

See: https://github.com/geerlingguy/drupal-vm/releases/tag/4.1.0

### PR DESCRIPTION
**Pull request by geerlingguy**
Fixes #898.

Changes proposed:
- Bump Drupal VM version requirement to `~4.1`.

### CODE REVIEW

**Comment by oxyc** [comment]
4.1.0 is broken https://github.com/geerlingguy/drupal-vm/issues/1093

**Comment by oxyc** [comment]
ping @geerlingguy needs 4.1.1 :)

**Comment by geerlingguy** [comment]
@oxyc - ~4.1 grabs the latest 4.1.x release, so it should still be good to go.

**Comment by oxyc** [comment]
Ah true...

**Pull request merged**
