### PR TITLE
Install drush launcher in VM and pin to 0.6.0.

### PR DESCRIPTION
**Pull request by lcatlett**
Changes proposed:
- Installs drush launcher to use vendored project drush
- Install 0.6.0 to resolve multisite --uri and --root bug

### CODE REVIEW

**Comment by ba66e77** [comment]
@lcatlett, can you give me some more background on what issue this PR addresses and what the testing steps are? Is there a related issue?

**Comment by lcatlett** [comment]
This resolves a bug in drush-launcher that was causing sqlc drush commands without an alias to fail if run outside of the vendored drush directory even if passing `--root=` and `--uri=`. see https://github.com/drush-ops/drush-launcher/pull/44

**Comment by ba66e77** [comment]
With this change in place, I destroyed my drupalvm instance, rm'ed the box directory, and re-ran `blt vm` to build a new VM. When drupalvm boots, I'm getting the following error

**Comment by ba66e77** [comment]
With `"yes"` I got the same results as when it was in single quotes. I ended up changing the line to `drush_launcher_install: true` and that seems to have gotten it installing correctly.

**Comment by ba66e77** [comment]
Following up from side conversations, it was determined that geerlingguy's drush role for DrupalVM already accomplishes this if the box is >=4.9. So we dont need this code but may want to update to require DrupalVM 4.9. 
> ./vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.drush/defaults/main.yml:3:drush_launcher_install: yes

**Pull request closed without merging**
