### PR TITLE
Change optimization package to symfony-clean-tags.

### PR DESCRIPTION
**Pull request by lcatlett**
Fixes # 
--------
Having `zaporylie/composer-drupal-optimizations` in the root `composer.json` appears to cause issues with autoloading classes in the correct place when using the `composer-merge` plugin (#3319) and also [hard codes the symfony version constraint](https://github.com/zaporylie/composer-drupal-optimizations/blob/master/src/Cache.php#L14) which may cause issues when updating core and other dependent packages unless `zaporylie/composer-drupal-optimizations` is actively maintained. 

Changes proposed:
---------
Use rubenrua/symfony-clean-tags-composer-plugin rather than zaporylie/composer-drupal-optimizations 

Steps to verify the solution:
-----------
benchmarks: 

```
~/sites/demo-project core-update
❯ COMPOSER_MEMORY_LIMIT=-1 composer update --profile --ignore-platform-reqs --dry-run                                        ⏎
[12.8MB/0.01s] Loading composer repositories with package information
[13.5MB/1.93s] Updating dependencies (including require-dev)
[447.0MB/34.05s] Memory usage: 447.05MB (peak: 1631.08MB), time: 34.05s


~/sites/demo-project core-update
❯ COMPOSER_MEMORY_LIMIT=-1 composer require rubenrua/symfony-clean-tags-composer-plugin                                      ⏎
Using version ^1.0 for rubenrua/symfony-clean-tags-composer-plugin
./composer.json has been updated


❯ COMPOSER_MEMORY_LIMIT=-1 composer config extra.symfony.require 3.4.*


~/sites/demo-project core-update*
❯ COMPOSER_MEMORY_LIMIT=-1 composer update --profile --ignore-platform-reqs --dry-run
[314.0MB/7.97s] Memory usage: 313.99MB (peak: 385.97MB), time: 7.97s
```

### CODE REVIEW

**Comment by geerlingguy** [comment]
I'm not seeing the `symfony-clean-tags` package added...?

**Comment by lcatlett** [comment]
> I'm not seeing the `symfony-clean-tags` package added...?

I suppose including the package might be helpful @geerlingguy  :stuck_out_tongue_winking_eye:.

I updated the original and will open one on 9.2 once tests pass...

**Comment by lcatlett** [comment]
@grasmash - I just updated the PR to remove `zaporylie/composer-drupal-optimizations`. unless we want to maintain a fork, it is causing autoloading issues to persist in BLT 9.2.x and 10.x

**Comment by grasmash** [comment]
I still see these notices:

```
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/tmp/blt-sandbox-instance/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
```

Is this PR intended to resolve these notices?

**Comment by lcatlett** [comment]
@grasmash - this was intended to just swap out `zaporylie/composer-drupal-optimizations` for `rubenrua/symfony-clean-tags-composer-plugin` rather than fully address the entire "Could not scan for classes " issue since I noticed it caused a recurrance of the error as I was debugging the larger issue, but I can update this PR with the progress I made

**Comment by lcatlett** [comment]
I put in a [PR](https://github.com/drupal-composer/drupal-project/pull/452) in the upstream drupal-project for this since `zaporylie/composer-drupal-optimizations` was added recently and would have introduced this regression to all BLT users. The maintainer of `composer-drupal-optimizations` [responded](https://github.com/drupal-composer/drupal-project/pull/452#issuecomment-458888505) to the queue that he's looking at addressing the issues so hopefully there wont be a need to include this at all in BLT since `drupal-project` will have the dependency already.

**Comment by danepowell** [comment]
It looks like zaporylie/composer-drupal-optimizations was finally updated to account for these issues, so no action is required by BLT. Additionally, drupal-project is still using it and I don't think we'd want to depart from drupal-project's lead on this.

From what I can tell then, this issue can be closed. Let me know if I'm missing anything.

**Pull request closed without merging**
