### PR TITLE
Add support for generating ACSF site aliases

### LINKED ISSUE #2914: ACSF alias generation
In BLT 8, we relied on ACSF Tools to allow people to dynamically generate ACSF aliases.

ACSF Tools no longer has alias generation in the 9.x branch, and we would like to roll that functionality into BLT 9.

### PR DESCRIPTION
**Pull request by lcatlett**
Fixes #2914 #2925  

Changes proposed:
- Adds support for generating ACSF site aliases without ACSF tools via `blt recipes:aliases:init:acquia`
- Supports non-acquia primary domains
- Sets appId config in blt.yml to disable interactive prompt.
- Fixes phpcs issues in previous task

### CODE REVIEW

**Comment by lcatlett** [comment]
This has been tested successfully on 5+ ACSF customers successfully with the largest customer having 192 sites.

**Comment by ba66e77** [comment]
I'm getting a PHP fatal immediately after entering the application id.  It looks like YamlMunge really lives in the Acquia\Blt\Robo\Common namespace and not in Acquia\Blt\Robo\Commands\Generate\YamlMunge.

```
$ blt recipes:aliases:init:acquia
[warning] Drupal VM is locally initialized, but is not running.
To generate an alias for the Acquia Cloud, BLT require's your Acquia Cloud application ID.
See https://docs.acquia.com/acquia-cloud/manage/applications.
 Please enter your Acquia Cloud application ID 8bd{redacted application id}17b61

Updating /Users/barrett.smith/Desktop/blted8/blt/blt.yml...

PHP Fatal error:  Uncaught Error: Class 'Acquia\Blt\Robo\Commands\Generate\YamlMunge' not found in /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php:105
Stack trace:
#0 /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php(90): Acquia\Blt\Robo\Commands\Generate\AliasesCommand->writeAppConfig('8bd...')
#1 /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php(55): Acquia\Blt\Robo\Commands\Generate\AliasesCommand->setAppId()
#2 [internal function]: Acquia\Blt\Robo\Commands\Generate\AliasesCommand->generateAliasesAcquia(Array)
#3 /Users/barrett.smith/Desktop/blted8/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#4 /Users/barrett.smith/Desktop/blted8/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /Users/barrett.smith/Desktop/blted8/ven in /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php on line 105

Fatal error: Uncaught Error: Class 'Acquia\Blt\Robo\Commands\Generate\YamlMunge' not found in /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php:105
Stack trace:
#0 /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php(90): Acquia\Blt\Robo\Commands\Generate\AliasesCommand->writeAppConfig('8bd...')
#1 /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php(55): Acquia\Blt\Robo\Commands\Generate\AliasesCommand->setAppId()
#2 [internal function]: Acquia\Blt\Robo\Commands\Generate\AliasesCommand->generateAliasesAcquia(Array)
#3 /Users/barrett.smith/Desktop/blted8/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#4 /Users/barrett.smith/Desktop/blted8/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /Users/barrett.smith/Desktop/blted8/ven in /Users/barrett.smith/Desktop/blt/src/Robo/Commands/Generate/AliasesCommand.php on line 105

**Comment by ba66e77** [comment]
Alias generation is working fine for both ACSF and ACE and when creating a new project the typhonius/acquia-php-sdk-v2 package is brought in on the dev-master branch. 

Forcing the acquia-php-sdk-v2 package to update from 1.0.2 when blt is updated on _existing_ projects is proving more difficult. In the end I had to manually require the package: `composer require typhonius/acquia-php-sdk-v2:dev-master`. Anyway we could put that in an update hook something?

**Comment by lcatlett** [comment]
@ba66e77 do you recall how you were updating BLT when you ran into the `typhonius/acquia-php-sdk-v2` conflict? I created an update hook but I am actually having difficulty re-creating this issue and testing it.

**Comment by ba66e77** [comment]
The process I was using to test the update path was:

1. Checkout the 9.x branch, run composer install, run the process to [create a blted8 from symlink]
(https://blt.readthedocs.io/en/stable/CONTRIBUTING/#developing-blt-locally)
1. Checkout this PR using `hub checkout`
1. Run composer install
1. Run `blt update`
1. Verify version in composer.json and composer.lock
1. Run process to generate aliases: `blt recipes:aliases:init:acquia`

**Comment by lcatlett** [comment]
I think instead of just running composer install you may need to run `composer update acquia/blt --update-with-dependencies` since the blt package might be using the cached dependencies due to the version number being the same. I will validate if that is the case and recommend either update testing steps or a hook

**Comment by lcatlett** [comment]
I've confirmed that you can update BLT with the needed toot dependencies by adding the ` --update-with-all-dependencies` parameter, even if these were locked by previous versions of BLT. The `dev-acsf-aliases` branch below is my local branch that is this PR.  

`composer require acquia/blt:dev-acsf-aliases --update-with-all-dependencies`

output:

```
vagrant@local /var/www/bltdev (test-update *) $ composer require acquia/blt:dev-acsf-aliases --update-with-all-dependencies
    1/7:	http://packagist.org/p/provider-latest$3be915d1e54e18e96f9c901b814591e116e5145a177f10355fa179459927110d.json
 [...]
    Finished: success: 7, skipped: 0, failure: 0, total: 7
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
 [...]
    Finished: success: 6, skipped: 0, failure: 0, total: 6
Package operations: 1 install, 12 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating typhonius/acquia-php-sdk-v2 (1.0.2 => dev-master 2e04652):  Checking out 2e046528a1
 [...]
Writing lock file
Generating autoload files
Updating BLT templated files...
 > blt blt:update --ansi -y
Copying files from BLT's template into your project...
Merging BLT's blt.yml template with your project's blt/blt.yml...
Removing deprecated files and directories...
> blt:init:shell-alias
The BLT alias is already installed and up to date.
```

It may be worth calling this out in the release notes to prevent similar update issues for users

**Pull request merged**
