### PR TITLE
Made cloud hooks executable.

### PR DESCRIPTION
**Pull request by danepowell**
Sorry I missed this. Cloud hooks won't run unless they are executable.

### CODE REVIEW

**Comment by seanhamlin** [comment]
That explains this error:

```
22: exec: /var/www/html/sitename.01test/hooks/common/post-code-deploy/post-code-deploy.sh: Permission denied[2016-11-14 08:10:07] 
```

Also, these fire for ACSF, is this expected?

**Comment by grasmash** [comment]
I suspect that we do not want this on ACSF.

**Comment by danepowell** [comment]
To my knowledge, cloud hooks are not supported on ACSF.

**Comment by seanhamlin** [comment]
@danepowell well the hooks do fire on ACSF, it is just that the environments are named differently (e.g. 01live, 01test), the `common` hooks fire. I would imagine it would make sense to verify you are running in ACE prior to invoking that blt script.

**Comment by kevinquillen** [comment]
Small note, I think this is the issue I just ran into. I generated a vanilla project, built it, deployed to Acquia Cloud. When switching to the build branch, it errored out because the hooks could not be executed. Support replied with:

```
chmod a+x hooks/common/post-code-deploy/post-code-deploy.sh
chmod a+x hooks/common/post-code-update/post-code-update.sh
git add hooks/common/post-code-deploy/post-code-deploy.sh
git add hooks/common/post-code-update/post-code-update.sh
git commit -m "Make the post-code hooks executable."
git push
```

**Pull request merged**
