### PR TITLE
Fixes #2566: Allow site to be installed from existing config.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by mikemadison13** [comment]
@grasmash should this (https://github.com/acquia/blt/pull/2590/commits/02d0f2cc1589e1627007bfac845484d018be873b#diff-3d8cbed0246f21f2e5dee994d04cb0f6R214) be system.site.yml?

**Comment by grasmash** [comment]
Yes!

**Comment by grasmash** [comment]
Adding @lcatlett and @danepowell for visibility.

**Comment by brooke-heaton** [comment]
@grasmash @mikemadison13 is there something I need to set in BLT config to install from a configuration directory? Or is this something I set in settings.php?

**Comment by brooke-heaton** [comment]
this happens on `blt sync` btw - it is not grabbing the UUID from my system.site.yml for some reason. I'm unclear why

**Comment by mikemadison13** [comment]
@brooke-heaton  what version of BLT are you running?

**Comment by brooke-heaton** [comment]
@mikemadison13 I'm on `9.1.0-alpha1`

Important background: This site was installed using the `standard` profile - long before we planned to move to BLT. I'm not sure if _that_ is a factor or not. I'm not clear on whether BLT _should_ just grab the UUID or import existing_config or what. :/

**Comment by danepowell** [comment]
I haven't used this functionality myself so it's hard for me to predict what's going wrong, but just based on your description, BLT _should_ be setting the site UUID. I'd suggest using `blt sync -vvv` to see the full list of commands that BLT is running--ensure that the `drush cset` is in there as expected, and that it's not getting "undone" by some later command.

**Pull request merged**
